import test from 'node:test';
import assert from 'node:assert/strict';
import {renderToStaticMarkup} from 'react-dom/server';
import {PublicationReview} from './PublicationReview';
import {PublicationController, safeDestination} from '../../lib/git/publication/controller';
import {createPublicationBackend, type PublicationBackend, type PublicationPlan, type PublicationTarget, type PublicationOutcome} from '../../lib/git/publication/types';
import {CATALOGUES} from '../../lib/i18n';
const target: PublicationTarget = {remote:'origin', sourceBranch:'feature/hero', targetBranch:'main', accountId:'owner', authRoute:'github-https'};
const plan = (patch: Partial<PublicationPlan> = {}): PublicationPlan => ({planId:'p1',contentHash:'tree1',head:'a'.repeat(40),remoteTip:'b'.repeat(40),account:{id:'owner',login:'philppplik'},authRoute:'github-https',repository:{name:'philppplik/demo',visibility:'private'},effectiveRemoteUrl:'https://github.com/philppplik/demo.git',destinationValidated:true,sourceBranch:'feature/hero',targetBranch:'main',commits:[{sha:'a'.repeat(40),subject:'Fix hero'}],untracked:['draft.txt'],excluded:['.env'],unsavedBuffers:0,initiatedBy:'human',...patch});
function fake(p=plan(), outcome: PublicationOutcome={kind:'published',sha:'a'.repeat(40),remote:'origin',targetBranch:'main'}) {
 const calls: unknown[]=[];
 const backend: PublicationBackend={plan:async req=>{calls.push(['plan',req]);return p;},apply:async req=>{calls.push(['apply',req]);return outcome;},fetch:async remote=>{calls.push(['fetch',remote]);}};
 return {calls,backend,c:new PublicationController(backend)};
}
test('publication needs explicit single-use confirmation bound to plan and hash',async()=>{const {c,calls}=fake();await c.review(target);await c.publish();assert.equal(calls.length,1);c.confirm(true);assert.equal(c.canApply(),true);await c.publish();assert.deepEqual(calls[1],['apply',{planId:'p1',contentHash:'tree1',confirmed:true}]);assert.equal(c.getState().outcome?.kind,'published');assert.equal(c.canApply(),false);await c.publish();assert.equal(calls.length,2);});
test('new review clears previous confirmation',async()=>{const {c}=fake();await c.review(target);c.confirm(true);await c.review(target);assert.equal(c.getState().confirmed,false);});
test('all typed failures and stale outcomes revoke approval; stale requires fetch',async()=>{for(const kind of ['stale-plan','denied-protection','denied-SSO','needs-auth','needs-workflow-scope','failed','uncertain-reconcile'] as const){const {c,calls}=fake(plan(),{kind});await c.review(target);c.confirm(true);await c.publish();assert.equal(c.canApply(),false);assert.equal(c.getState().plan,null);if(kind==='uncertain-reconcile'){await c.review(target);assert.equal(calls.length,2);}await c.review(target,true);assert.deepEqual(calls[2],['fetch','origin']);assert.equal(c.getState().confirmed,false);}});
test('transport exception is uncertain, never presumed failed or published',async()=>{const {c,backend}=fake();backend.apply=async()=>{throw Error('raw secret transport text');};await c.review(target);c.confirm(true);await c.publish();assert.equal(c.getState().outcome?.kind,'uncertain-reconcile');assert.ok(!JSON.stringify(c.getState()).includes('raw secret'));});
test('agent unsaved buffers and missing grants are hard blockers',async()=>{for(const p of [plan({initiatedBy:'agent'}),plan({initiatedBy:'agent',grant:{id:'g1',label:'Reviewed task'},unsavedBuffers:1})]){const {c,calls}=fake(p);await c.review(target);c.confirm(true);await c.publish();assert.equal(calls.length,1);}const {c}=fake(plan({initiatedBy:'agent',grant:{id:'g1',label:'Reviewed task'}}));await c.review(target);c.confirm(true);assert.equal(c.canApply(),true);c.setUnsaved(1);c.confirm(true);assert.equal(c.canApply(),false);});
test('manual dirty buffers warn but only committed versions can publish',async()=>{const {c}=fake();c.setUnsaved(2);await c.review(target);c.confirm(true);assert.equal(c.canApply(),true);});
test('unsafe URL or mismatched account, route or branches fails closed',async()=>{for(const patch of [{effectiveRemoteUrl:'https://token@github.com/philppplik/demo.git'},{effectiveRemoteUrl:'https://github.com/philppplik/demo.git?token=x'},{effectiveRemoteUrl:'https://evil.invalid/philppplik/demo.git'},{destinationValidated:false},{contentHash:''},{account:{id:'other',login:'other'}},{authRoute:'gcm' as const},{sourceBranch:'other'},{targetBranch:'other'}]){const {c}=fake(plan(patch));await c.review(target);assert.equal(c.getState().plan,null);assert.equal(c.getState().error,true);}});
test('empty publication cannot apply and source-of-truth validation is required',async()=>{const {c}=fake(plan({commits:[]}));await c.review(target);c.confirm(true);assert.equal(c.canApply(),false);assert.equal(safeDestination(plan({destinationValidated:false})),false);});
test('invalidation removes plan and prevents publishing',async()=>{const {c}=fake();await c.review(target);c.confirm(true);c.invalidate();assert.equal(c.canApply(),false);assert.equal(c.getState().outcome?.kind,'stale-plan');});
test('adapter invokes plan/apply/fetch without credentials',async()=>{const calls: unknown[]=[];const b=createPublicationBackend(async <T,>(cmd:string,args?:Record<string,unknown>)=>{calls.push([cmd,args]);return undefined as T;});await b.plan(target);await b.apply({planId:'p1',contentHash:'tree1',confirmed:true});await b.fetch('origin');assert.deepEqual(calls.map((x:any)=>x[0]),['git_push_plan','git_push_apply','git_fetch']);assert.ok(!/token|password/i.test(JSON.stringify(calls)));});
test('all publication keys have five-locale parity and placeholders match',()=>{const keys=Object.keys(CATALOGUES.en).filter(k=>k.startsWith('publication.'));assert.ok(keys.length>40);for(const locale of ['de','es','fr','pt-BR']){assert.deepEqual(Object.keys(CATALOGUES[locale]).filter(k=>k.startsWith('publication.')).sort(),[...keys].sort());for(const k of keys)assert.deepEqual(CATALOGUES[locale][k].match(/\{\w+\}/g),CATALOGUES.en[k].match(/\{\w+\}/g));}});
test('SSR review entry has explicit account and branch inputs without auto publishing',()=>{const {backend,calls}=fake();const html=renderToStaticMarkup(<PublicationReview backend={backend} unsavedFiles={0} advanced={false}/>);assert.ok(html.includes('publication-accountId')&&html.includes('publication-targetBranch'));assert.equal(calls.length,0);});
test('changing target cannot erase uncertainty or reconcile the wrong remote',async()=>{const {c,calls}=fake(plan(),{kind:'uncertain-reconcile'});await c.review(target);c.confirm(true);await c.publish();c.invalidate();assert.equal(c.getState().outcome?.kind,'uncertain-reconcile');await c.review({...target,remote:'other'});assert.equal(calls.length,2);await c.review({...target,remote:'other'},true);assert.deepEqual(calls[2],['fetch','origin']);});
test('stale-plan cannot be reviewed again without fetch',async()=>{const {c,calls}=fake(plan(),{kind:'stale-plan'});await c.review(target);c.confirm(true);await c.publish();await c.review(target);assert.equal(calls.length,2);await c.review(target,true);assert.deepEqual(calls[2],['fetch','origin']);});
