import {test,expect} from '@playwright/test';
async function open(page:import('@playwright/test').Page,locale='en',theme='light'){
 await page.addInitScript(l=>localStorage.setItem('somnia.locale.v1',l),locale);
 await page.goto('/agent-board.html?theme='+theme);await expect(page.locator('.ab-card')).toHaveCount(5);
}
test('review handoff and current-content invalidation',async({page})=>{
 await open(page);const card=page.locator('[data-task="task-review"]');await card.getByRole('button',{name:'Review changes'}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.screenshot({path:'/downloads/agent-board-hunk-review.png'});await page.getByRole('button',{name:'Accept all',exact:true}).click();await page.evaluate(()=> (window as any).boardFixture.stale());await expect(page.getByRole('alert').filter({hasText:'Open a fresh review'})).toBeVisible();await expect(page.getByRole('button',{name:'Confirm review'})).toHaveCount(0);await page.screenshot({path:'/downloads/agent-board-stale-review.png'});
});
test('unsaved-buffer blocker prevents review and retry',async({page})=>{await open(page);await page.evaluate(()=> (window as any).boardFixture.setDirty(true));await page.locator('[data-task="task-review"]').getByRole('button',{name:'Review changes'}).click();await expect(page.getByRole('alert')).toHaveText(/Save unsaved buffers/);await expect(page.getByRole('dialog')).toHaveCount(0);await page.locator('[data-task="task-failed"]').getByRole('button',{name:'Retry task'}).click();expect(await page.evaluate(()=> (window as any).boardFixture.events)).toEqual([]);});
test('review, combine, cancel and retry use engine actions',async({page})=>{await open(page);const card=page.locator('[data-task="task-review"]');await card.getByRole('button',{name:'Review changes'}).click();await page.getByRole('button',{name:'Accept all',exact:true}).click();await page.getByRole('button',{name:'Confirm review'}).click();await card.getByRole('button',{name:'Combine variant'}).click();await page.locator('[data-task="task-running"]').getByRole('button',{name:'Cancel task'}).click();await page.locator('[data-task="task-failed"]').getByRole('button',{name:'Retry task'}).click();expect(await page.evaluate(()=> (window as any).boardFixture.events)).toEqual(['review:task-review','combine:task-review','cancel:task-running','retry:task-failed']);});
test('export only saves after human preview',async({page})=>{await open(page);await page.locator('[data-task="task-done"]').getByRole('button',{name:'Export session'}).click();const d=page.getByRole('dialog');await expect(d.locator('pre')).not.toContainText(/secret|transcript|apiKey/);expect(await page.evaluate(()=> (window as any).boardFixture.events)).toEqual([]);await page.screenshot({path:'/downloads/agent-board-export-preview.png'});await d.getByRole('button',{name:'Save private export'}).click();expect(await page.evaluate(()=> (window as any).boardFixture.events)).toEqual(['export:task-done']);});
for(const locale of ['en','de','es','fr','pt-BR'])for(const theme of ['light','dark'])test(`screenshot ${locale} ${theme}`,async({page})=>{await open(page,locale,theme);await page.screenshot({path:`/downloads/agent-board-${locale}-${theme}.png`,fullPage:true});await expect(page.locator('.ab-board')).toBeVisible();expect(await page.locator('.ab-board').innerText()).not.toContain('board.');});

test("mobile board stacks without clipping",async({page})=>{await page.setViewportSize({width:390,height:844});await open(page,"de","dark");await page.screenshot({path:"/downloads/agent-board-mobile.png",fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);});

test("German hunk controls use localized keys",async({page})=>{await open(page,"de","dark");await page.locator('[data-task="task-review"]').getByRole("button",{name:"Änderungen prüfen"}).click();await expect(page.getByRole("button",{name:"Alle annehmen",exact:true})).toBeVisible();await page.screenshot({path:"/downloads/agent-board-hunk-review-de-dark.png"});});
