import {test,expect} from '@playwright/test';
const open=async(page:import('@playwright/test').Page)=>{await page.goto('/');await page.getByRole('button',{name:'Open Somnia Agent'}).click();return page.getByRole('complementary',{name:'Somnia Agent'});};
test('opener sits at the bottom of the right rail and toggles the panel',async({page})=>{await page.goto('/');
 const rail=page.getByRole('toolbar',{name:'Inspector panels'});const btn=rail.getByRole('button',{name:'Open Somnia Agent'});
 await expect(btn).toBeVisible();await expect(btn).toHaveAttribute('aria-pressed','false');
 await expect(btn.locator('svg[data-icon="vadivam:sparkles"]')).toHaveCount(1);
 const rb=await rail.boundingBox(),bb=await btn.boundingBox();expect(bb!.y+bb!.height).toBeGreaterThan(rb!.y+rb!.height-24);
 await btn.click();await expect(page.getByRole('complementary',{name:'Somnia Agent'})).toBeVisible();await expect(btn).toHaveAttribute('aria-pressed','true');
 await page.getByRole('button',{name:'Collapse panel'}).click();await expect(page.getByRole('complementary',{name:'Somnia Agent'})).toHaveCount(0);});
test('empty state shows tip and chips; panel has a bottom gradient only',async({page})=>{const panel=await open(page);
 await expect(panel.getByRole('heading',{name:'What are we building?'})).toBeVisible();await expect(panel.getByText('Use @ to refer')).toBeVisible();
 await expect(panel.getByRole('button',{name:'Help me design a landing page'})).toBeVisible();
 await expect(panel.locator('.ag-bar')).toHaveCount(1);
 const bar=await panel.locator('.ag-bar').boundingBox(),pb=await panel.boundingBox();expect(bar!.y+bar!.height).toBeCloseTo(pb!.y+pb!.height,0);
 await expect(panel.getByRole('button',{name:'Send'})).toBeDisabled();});
test('chat flow: send, stream, stop, diff accept and undo, new chat',async({page})=>{const panel=await open(page);
 const input=panel.getByLabel('Message to Somnia Agent');await input.fill('Make the headline bigger');await input.press('Enter');
 await expect(panel.locator('.ag-u')).toHaveText('Make the headline bigger');
 await expect(panel.getByRole('button',{name:'Stop'})).toBeVisible();await expect(input).toBeDisabled();
 await expect(panel.locator('.ag-diff')).toBeVisible({timeout:8000});
 await expect(panel.getByRole('button',{name:'Send'})).toBeVisible();await expect(input).toBeEnabled();
 await panel.getByRole('button',{name:'Accept'}).click();await expect(panel.getByText('Accepted')).toBeVisible();
 await panel.getByRole('button',{name:'Undo'}).click();await expect(panel.getByRole('button',{name:'Accept'})).toBeVisible();
 await panel.getByRole('button',{name:'Reject'}).click();await expect(panel.getByText('Rejected')).toBeVisible();
 await panel.getByRole('button',{name:'New chat'}).click();await expect(panel.getByRole('heading',{name:'What are we building?'})).toBeVisible();});
test('stop ends a running answer without a diff',async({page})=>{const panel=await open(page);
 await panel.getByRole('button',{name:'Help me design a landing page'}).click();await panel.getByRole('button',{name:'Stop'}).click();
 await expect(panel.getByRole('button',{name:'Send'})).toBeVisible();await page.waitForTimeout(500);await expect(panel.locator('.ag-diff')).toHaveCount(0);});
test('shortcut Ctrl+Alt+A toggles the panel and settings button opens app settings',async({page})=>{await page.goto('/');
 await page.keyboard.press('Control+Alt+a');const panel=page.getByRole('complementary',{name:'Somnia Agent'});await expect(panel).toBeVisible();
 await panel.getByRole('button',{name:'Settings'}).click();await expect(page.getByRole('dialog')).toBeVisible();});
