import {test,expect} from './fixtures';
import {showCode} from './helpers';
test('real canvas selects and plain text editing preserves source; shared undo',async({page})=>{
 await page.goto('/');const frame=page.frameLocator('iframe[title="Sandboxed design preview"]');await expect(frame.locator('h1')).toHaveText('Make room for something new.');await frame.locator('h1').click();await expect(page.getByLabel('Element ID',{exact:true})).toBeVisible();await frame.locator('h1').dblclick();await page.getByLabel('Canvas text edit').fill('New local idea');await page.getByLabel('Canvas text edit').press('Control+Enter');await expect(frame.locator('h1')).toHaveText('New local idea');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(frame.locator('h1')).toHaveText('Make room for something new.');await page.screenshot({path:'tests/artifacts/integrated-canvas.png'});
});
test('project scripts and inline events cannot execute or load remote resources',async({page})=>{
 await page.goto('/');await showCode(page);const src=page.getByLabel('Source code');await src.fill('<!doctype html><html><head></head><body><h1 onclick="document.body.dataset.pwned=1">Safe</h1><script>parent.document.body.dataset.pwned=1</script><img src="https://tracker.example.invalid/a"><iframe src="https://evil.example.invalid"></iframe></body></html>');await page.getByRole('button',{name:'Design view',exact:true}).click();const f=page.frameLocator('iframe[title="Sandboxed design preview"]');await expect(f.locator('h1')).toHaveText('Safe');await f.locator('h1').click();await expect(page.locator('body')).not.toHaveAttribute('data-pwned');await expect(f.locator('script')).toHaveCount(0);await expect(f.locator('iframe')).toHaveCount(0);await expect(f.locator('img')).not.toHaveAttribute('src');await expect(f.locator('h1')).not.toHaveAttribute('onclick');
});
test('visual CSS goes to external source and breakpoint remains scoped',async({page})=>{
 await page.goto('/');const f=page.frameLocator('iframe[title="Sandboxed design preview"]');await f.locator('h1').click();await page.getByLabel('CSS property',{exact:true}).selectOption('color');await page.getByLabel('CSS value',{exact:true}).fill('#123456');await page.getByRole('button',{name:'Apply CSS rule',exact:true}).click();await expect(f.locator('h1')).toHaveCSS('color','rgb(18, 52, 86)');await page.getByRole('button',{name:'Mobile viewport',exact:true}).click();await page.getByLabel('CSS value',{exact:true}).fill('#654321');await page.getByRole('button',{name:'Apply CSS rule',exact:true}).click();await expect(f.locator('h1')).toHaveCSS('color','rgb(101, 67, 33)');await page.getByRole('button',{name:'Desktop viewport',exact:true}).click();await expect(f.locator('h1')).toHaveCSS('color','rgb(18, 52, 86)');
});
test('shift selection applies one CSS transaction and resize changes real layout',async({page})=>{
 await page.goto('/');const f=page.frameLocator('iframe[title="Sandboxed design preview"]');await f.locator('h1').click();await f.locator('p').click({modifiers:['Shift']});await page.getByLabel('CSS value',{exact:true}).fill('#225588');await page.getByRole('button',{name:'Apply CSS rule',exact:true}).click();await expect(f.locator('h1')).toHaveCSS('color','rgb(34, 85, 136)');await expect(f.locator('p')).toHaveCSS('color','rgb(34, 85, 136)');await f.locator('h1').click();const handle=page.getByRole('button',{name:'Resize selection',exact:true});const box=await handle.boundingBox();if(!box)throw Error('Resize handle absent');await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+25,box.y+box.height/2+20,{steps:5});await page.mouse.up();await expect(f.locator('h1')).not.toHaveCSS('height','38px');await page.screenshot({path:'tests/artifacts/resize.png'});
});
test('range mini toolbar formats a plain leaf without replacing the rest; lock prevents edits',async({page})=>{
 await page.goto('/');const f=page.frameLocator('iframe[title="Sandboxed design preview"]');await f.locator('h1').dblclick();const input=page.getByLabel('Canvas text edit');await input.evaluate((el:any)=>{el.focus();el.setSelectionRange(0,4);el.dispatchEvent(new Event('select',{bubbles:true}));});await page.screenshot({path:'tests/artifacts/richtext-toolbar.png'});await page.getByRole('button',{name:'Format strong',exact:true}).click();await expect(f.locator('h1 strong')).toHaveText('Make');await expect(f.locator('h1')).toHaveText('Make room for something new.');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(f.locator('h1 strong')).toHaveCount(0);await page.getByRole('button',{name:'Lock h1',exact:true}).click();await f.locator('h1').dblclick();await expect(page.getByLabel('Canvas text edit')).toHaveCount(0);await page.getByRole('button',{name:'Hide h1',exact:true}).click();await expect(f.locator('h1')).toBeHidden();await page.getByRole('button',{name:'Show h1',exact:true}).click();await expect(f.locator('h1')).toBeVisible();
});
test('padding drag uses current computed padding and commits one real CSS change',async({page})=>{
 await page.goto('/');const f=page.frameLocator('iframe[title="Sandboxed design preview"]');await f.locator('section').click({position:{x:30,y:30}});await expect(page.getByLabel('Padding computed',{exact:true})).toHaveValue('80px');const handle=page.getByRole('button',{name:'Drag padding',exact:true});const box=await handle.boundingBox();if(!box)throw Error('padding handle absent');await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2,box.y+box.height/2+12,{steps:5});await page.mouse.up();await expect(page.getByLabel('Padding computed',{exact:true})).not.toHaveValue('80px');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByLabel('Padding computed',{exact:true})).toHaveValue('80px');
});

test('mixed inline text ranges preserve original markup and entities through shared undo',async({page})=>{
 await page.goto('/');await showCode(page);await page.getByLabel('Source code').fill('<!doctype html><html><head></head><body><h1>Hi <em data-x="keep">big &amp; bold</em><!--keep--> world</h1></body></html>');await page.getByRole('button',{name:'Design view',exact:true}).click();const f=page.frameLocator('iframe[title="Sandboxed design preview"]');await f.locator('h1').dblclick({position:{x:3,y:8}});const input=page.getByLabel('Canvas text edit');await input.evaluate((el:any)=>{el.focus();el.setSelectionRange(1,19);el.dispatchEvent(new Event('select',{bubbles:true}));});await page.getByRole('button',{name:'Format strong',exact:true}).click();await expect(f.locator('h1 strong')).toHaveCount(3);await expect(f.locator('h1 em')).toHaveAttribute('data-x','keep');await expect(f.locator('h1')).toHaveText('Hi big & bold world');await page.screenshot({path:'tests/artifacts/mixed-inline-format.png'});await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(f.locator('h1 strong')).toHaveCount(0);await expect(f.locator('h1 em')).toHaveText('big & bold');
});

test('HTML elements insert into source container and layer reorder shares undo',async({page})=>{await page.goto('/');const f=page.frameLocator('iframe[title="Sandboxed design preview"]');await f.locator('section').click({position:{x:25,y:25}});await page.getByRole('button',{name:'Components panel',exact:true}).click();await page.getByRole('button',{name:'Paragraph',exact:true}).click();await expect(f.locator('section p')).toHaveCount(2);await expect(f.locator('section p').last()).toHaveText('New paragraph');await page.getByRole('button',{name:'Layers panel',exact:true}).click();await page.getByRole('button',{name:'Move p up',exact:true}).last().click();await expect(f.locator('section').locator(':scope > *').nth(2)).toHaveText('New paragraph');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(f.locator('section').locator(':scope > *').last()).toHaveText('New paragraph');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(f.locator('section p')).toHaveCount(1);await page.getByRole('button',{name:'Components panel',exact:true}).click();await page.screenshot({path:'tests/artifacts/html-elements-light.png'});});
test('real drag from HTML library inserts into sandbox source container',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'Components panel',exact:true}).click();const f=page.frameLocator('iframe[title="Sandboxed design preview"]');await page.getByRole('button',{name:'Heading',exact:true}).dragTo(f.locator('section'));await expect(f.locator('section h2')).toHaveText('New heading');await page.screenshot({path:'tests/artifacts/html-drag-drop.png'});await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(f.locator('section h2')).toHaveCount(0);});

test('authored fake selection IDs cannot hijack source editing',async({page})=>{await page.goto('/');await showCode(page);const source='<!doctype html><html><head></head><body><h1 data-editor-node="forged">Untouched</h1><p data-editor-node="forged">Target</p></body></html>';await page.getByLabel('Source code').fill(source);await page.getByRole('button',{name:'Design view',exact:true}).click();const f=page.frameLocator('iframe[title="Sandboxed design preview"]');await expect(f.locator('p')).not.toHaveAttribute('data-editor-node','forged');await expect(async()=>{await f.locator('p').dblclick();await expect(page.getByLabel('Canvas text edit')).toBeVisible({timeout:3000});}).toPass({timeout:20000});await page.getByLabel('Canvas text edit').fill('Correct target');await page.getByLabel('Canvas text edit').press('Control+Enter');await expect(f.locator('h1')).toHaveText('Untouched');await expect(f.locator('p')).toHaveText('Correct target');await page.getByRole('button',{name:'Code view',exact:true}).click();await expect(page.getByLabel('Source code')).toHaveText(source.replace('>Target<','>Correct target<'));});
