import {test,expect} from './fixtures';
import {openMine} from './helpers';
const original='<article class="compact"><h2 data-somnia-prop-text="title">Default</h2><a data-somnia-prop-link="cta" href="/original">Go</a><img data-somnia-prop-image="photo" src="/old.png" alt="Sample"><div data-somnia-slot="body"><p>Default content</p></div></article>';
const wide='<article class="wide"><h2 data-somnia-prop-text="title">Wide</h2><a data-somnia-prop-link="cta" href="/wide">More</a><img data-somnia-prop-image="photo" src="/wide.png" alt="Sample"><div data-somnia-slot="body">Wide content</div></article>';
test('instance text, link, image and slot survive switch, undo, reload and reset',async({page})=>{
 await page.addInitScript(({original,wide})=>{if(!localStorage.getItem('somnia.components.v2'))localStorage.setItem('somnia.components.v2',JSON.stringify([{id:'card',name:'Card props',defaultVariantId:'compact',variants:[{id:'compact',name:'Compact',html:original},{id:'wide',name:'Wide',html:wide}]}]));},{original,wide});
 await page.goto('/');const f=page.frameLocator('iframe[title="Sandboxed design preview"]');await expect(f.locator('h1')).toBeVisible();
 await page.getByRole('button',{name:'main',exact:true}).click();await openMine(page);await page.getByRole('button',{name:'Insert Card props Compact',exact:true}).click();
 await page.getByRole('button',{name:'Layers panel',exact:true}).click();await page.getByRole('button',{name:'article',exact:true}).click();await openMine(page);
 for(const [kind,name,value] of [['text','title','My title <not markup>'],['link','cta','/custom?x=1&y=2'],['image','photo','/custom.png'],['slot','body','<p><strong>Custom slot</strong></p>']]){await page.getByLabel(`Instance ${kind} ${name}`,{exact:true}).fill(value);await page.getByRole('button',{name:`Apply ${name}`,exact:true}).click();}
 const instance=f.locator('article[data-somnia-component="card"]');await expect(instance.locator('h2')).toHaveText('My title <not markup>');await expect(page.getByLabel('Instance link cta',{exact:true})).toHaveValue('/custom?x=1&y=2');await expect(page.getByLabel('Instance image photo',{exact:true})).toHaveValue('/custom.png');
 const source=await page.evaluate(async()=>{const {getState}=await import('/src/store/appStore.ts');return getState().files['index.html'];});expect(source).toContain('href="/custom?x=1&amp;y=2"');expect(source).toContain('src="/custom.png"');await expect(instance.locator('strong')).toHaveText('Custom slot');
 await page.getByRole('group',{name:'Selected component instance'}).getByRole('button',{name:'Wide',exact:true}).click();await expect(instance).toHaveClass('wide');await expect(instance.locator('h2')).toHaveText('My title <not markup>');await expect(instance.locator('strong')).toHaveText('Custom slot');
 await page.keyboard.press('Control+z');await expect(instance).toHaveClass('compact');await expect(instance.locator('h2')).toHaveText('My title <not markup>');
 await page.getByRole('group',{name:'Selected component instance'}).getByRole('button',{name:'Wide',exact:true}).click();await page.getByRole('button',{name:'Reset title',exact:true}).click();await expect(instance.locator('h2')).toHaveText('Wide');
 await page.getByRole('group',{name:'Selected component instance'}).getByRole('button',{name:'Compact',exact:true}).click();await expect(instance.locator('h2')).toHaveText('Default');await expect(instance.locator('strong')).toHaveText('Custom slot');
 await page.getByRole('group',{name:'Instance props and slots'}).screenshot({path:'tests/artifacts/component-props-fields.png'});await page.screenshot({path:'tests/artifacts/component-props-light.png'});
 await page.waitForTimeout(3600);await page.reload();await expect(instance.locator('strong')).toHaveText('Custom slot');const restored=await page.evaluate(async()=>{const {getState}=await import('/src/store/appStore.ts');return getState().files['index.html'];});expect(restored).toContain('href="/custom?x=1&amp;y=2"');
});
test('expose text from the selected element then save parent component',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'h1',exact:true}).click();await openMine(page);await page.getByText('Expose a prop or slot',{exact:true}).click();await page.getByLabel('Exposed field name').fill('heading');await page.getByRole('button',{name:'Expose selected element',exact:true}).click();await expect(page.getByRole('status')).toContainText('Exposed text field');const f=page.frameLocator('iframe[title="Sandboxed design preview"]');await expect(f.locator('h1')).toHaveAttribute('data-somnia-prop-text','heading');
});
test('invalid URL and duplicate source IDs in slots refuse without modifying the instance',async({page})=>{
 await page.addInitScript(original=>localStorage.setItem('somnia.components.v2',JSON.stringify([{id:'card',name:'Card props',defaultVariantId:'compact',variants:[{id:'compact',name:'Compact',html:original}]}])),original);
 await page.goto('/');await page.getByRole('button',{name:'main',exact:true}).click();await openMine(page);await page.getByRole('button',{name:'Insert Card props Compact',exact:true}).click();await page.getByRole('button',{name:'Layers panel',exact:true}).click();await page.getByRole('button',{name:'article',exact:true}).click();await openMine(page);
 await page.getByLabel('Instance link cta',{exact:true}).fill('javascript:alert(1)');await page.getByRole('button',{name:'Apply cta',exact:true}).click();await expect(page.getByRole('status')).toContainText('Nothing was changed');
 await page.getByLabel('Instance slot body',{exact:true}).fill('<p id="main">Duplicate</p>');await page.getByRole('button',{name:'Apply body',exact:true}).click();await expect(page.getByRole('status')).toContainText('repeat the source ID');
 const source=await page.evaluate(async()=>{const {getState}=await import('/src/store/appStore.ts');return getState().files['index.html'];});expect(source).not.toContain('javascript:');expect(source).not.toContain('Duplicate');
});
