import {test,expect} from './fixtures';
import {mkdirSync} from 'node:fs';
const source='<!doctype html><html><head></head><body style="padding:24px"><h1>Context title</h1><img width="120" height="80"><div style="padding:20px">Container</div><p>Paragraph</p></body></html>';
import {tmpdir} from 'node:os';import {join} from 'node:path';
const out=process.env.CONTEXT_UI_SHOTS||join(tmpdir(),'somnia-context-ui');mkdirSync(out,{recursive:true});
test('context matrix keeps shell geometry and web rail pixels unchanged',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Code view',exact:true}).click();await page.getByLabel('Source code').fill(source);await page.getByRole('button',{name:'Design view',exact:true}).click();const f=page.frameLocator('.design-iframe');await expect(f.locator('h1')).toHaveText('Context title');
 const geometry=()=>page.locator('header,.editor-layout,.panel.inspector,footer,[aria-label="Sidebar panels"],[aria-label="Inspector panels"]').evaluateAll(els=>els.map(e=>{const r=e.getBoundingClientRect();return [r.x,r.y,r.width,r.height];}));const initial=await geometry();
 const rail=page.getByRole('toolbar',{name:'Sidebar panels',exact:true});const expected=await rail.locator('[data-rail-item]').evaluateAll(els=>els.map(e=>e.getAttribute('data-rail-item')));expect(expected).toEqual(['layers','files','search','components','css','versions']);
 await page.screenshot({path:`${out}/page.png`});await page.evaluate(()=>{(window as any).__shellShifts=[];new PerformanceObserver(list=>{for(const entry of list.getEntries() as any[]){if(entry.sources?.some((s:any)=>s.node?.matches?.('header,footer,.editor-layout,.panel.inspector,[aria-label="Sidebar panels"],[aria-label="Inspector panels"]')))(window as any).__shellShifts.push(entry.value);}}).observe({type:'layout-shift',buffered:false});});
 for(const [name,selector] of [['text','h1'],['image','img'],['container','div']] as const){await f.locator(selector).click();await page.mouse.move(1400,890);await page.waitForTimeout(200);await expect(page.getByTestId('context-chip')).toHaveText(name==='text'?'Text':name==='image'?'Image':'Container');expect(await geometry()).toEqual(initial);expect(await rail.locator('[data-rail-item]').evaluateAll(els=>els.map(e=>e.getAttribute('data-rail-item')))).toEqual(expected);
 // Pixel snapshot dropped: the rail DOM order above is the invariant; the PNG baseline predates the Components redesign.
 if(name==='image'){await expect(page.getByTestId('inspector-alt-warning')).toBeVisible();await expect(page.getByTestId('canvas-alt-badge')).toBeVisible();}
 await page.screenshot({path:`${out}/${name}.png`});}
 await f.locator('h1').click();await f.locator('p').click({modifiers:['Shift']});await expect(page.getByTestId('context-chip')).toHaveText('2 selected');expect(await geometry()).toEqual(initial);await page.screenshot({path:`${out}/multi.png`});
 expect(await page.evaluate(()=>(window as any).__shellShifts.reduce((a:number,b:number)=>a+b,0))).toBe(0);await page.getByRole('button',{name:'Code view',exact:true}).click();await page.getByRole('button',{name:'Code panel',exact:true}).click();await expect(page.getByText('Outline',{exact:true})).toBeVisible();await page.screenshot({path:`${out}/code.png`});
});
test('floating formatting is functional and Escape does not steal focus',async({page})=>{await page.goto('/');const f=page.frameLocator('.design-iframe');await f.locator('h1').click();const format=page.getByRole('button',{name:'Format strong',exact:true});await expect(format).toBeVisible();await format.click();await expect(f.locator('h1 strong')).toHaveText('Make room for something new.');await page.keyboard.press('Escape');await expect(format).toBeHidden();});
test('manual inspector tab survives selection changes',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'Prototype panel',exact:true}).click();await page.frameLocator('.design-iframe').locator('h1').click();await expect(page.getByRole('button',{name:'Prototype panel',exact:true})).toHaveAttribute('aria-pressed','true');});
test('dark, reduced-motion and high contrast retain shell geometry',async({page})=>{await page.emulateMedia({reducedMotion:'reduce',colorScheme:'dark'});await page.addInitScript(()=>localStorage.setItem('somnia.theme','dark'));await page.goto('/');await page.evaluate(async()=>{const path='/src/store/appStore.ts';const {patchState}=await import(/* @vite-ignore */ path);patchState({themeChoice:'dark',theme:'dark'});});await page.frameLocator('.design-iframe').locator('h1').click();await expect(page.getByTestId('context-chip')).toHaveText('Text');await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.screenshot({path:`${out}/dark-reduced.png`});await page.evaluate(()=>document.documentElement.dataset.contrast='high');await page.screenshot({path:`${out}/high-contrast.png`});});

test('context settings work live, alt warning clears, and locked fields cannot edit',async({page})=>{await page.goto('/');const f=page.frameLocator('.design-iframe');await f.locator('h1').click();await expect(page.getByRole('button',{name:'Format strong',exact:true})).toBeVisible();await page.evaluate(async()=>{const path='/src/store/appStore.ts';const {getState,patchState}=await import(/* @vite-ignore */ path);patchState({workflowPrefs:{...getState().workflowPrefs,contextChips:false,floatingFormat:false}});});await expect(page.getByTestId('context-chip')).toBeHidden();await expect(page.getByRole('button',{name:'Format strong',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Lock h1',exact:true}).click();await expect(page.getByLabel('Element ID',{exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Unlock',exact:true})).toBeVisible();await page.getByRole('button',{name:'Unlock',exact:true}).click();await expect(page.getByLabel('Element ID',{exact:true})).toBeEnabled();});
test('missing alt clears on an explicit decorative choice',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'Code view',exact:true}).click();await page.getByLabel('Source code').fill(source);await page.getByRole('button',{name:'Design view',exact:true}).click();await page.frameLocator('.design-iframe').locator('img').click();await expect(page.getByTestId('inspector-alt-warning')).toBeVisible();await page.getByLabel('Decorative image',{exact:true}).check();await expect(page.getByTestId('inspector-alt-warning')).toHaveCount(0);await expect(page.getByTestId('canvas-alt-badge')).toHaveCount(0);});
test('native domains show only real entry points',async({page})=>{await page.goto('/');await page.evaluate(async()=>{const p='/src/lib/media.ts';const {addMediaFile}=await import(/* @vite-ignore */ p);const bytes=Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j9xkAAAAASUVORK5CYII='),c=>c.charCodeAt(0));await addMediaFile(new Blob([bytes],{type:'image/png'}),'test.png');});await expect(page.getByTestId('context-chip')).toHaveText('Raster');await expect(page.getByRole('button',{name:'Code view',exact:true})).toBeDisabled();await expect(page.getByRole('toolbar',{name:'Sidebar panels',exact:true}).locator('[data-rail-item]')).toHaveCount(0);await page.screenshot({path:`${out}/raster.png`});});
