import {test,expect} from '@playwright/test';
test('native adapter reads real IPC revisions, preserves dirty on rejected stage and retries exact save',async({page})=>{
 await page.addInitScript(()=>{
  const w=window as any;w.isTauri=true;let next=0;const callbacks=new Map();const handlers=new Map();w.ipcCalls=[];w.rejectStage=true;
  const disk:Record<string,string>={'index.html':'<!doctype html><html><head></head><body><h1>Disk title</h1></body></html>'};const pending:Record<string,{content:string;clientRevision:number}>={};
  w.__TAURI_INTERNALS__={metadata:{currentWindow:{label:'main'},currentWebview:{label:'main'}},transformCallback:(fn:any)=>{callbacks.set(++next,fn);return next;},invoke:async(cmd:string,args:any)=>{w.ipcCalls.push({cmd,args});if(cmd==='plugin:event|listen'){handlers.set(args.event,args.handler);return next;}if(cmd==='choose_project')return {projectId:'p1',name:'Native fixture'};if(cmd==='list_files')return Object.keys(disk);if(cmd==='recovery_list')return [];if(cmd==='read_file')return {content:disk[args.path]??null,revision:{exists:args.path in disk,hash:args.path in disk?'disk-hash':null},status:{}};if(cmd==='stage_edit'){if(w.rejectStage)throw 'simulated journal failure';pending[args.path]=args;return {projectId:'p1',path:args.path,clientRevision:args.clientRevision,state:'dirty',diskRevision:{exists:true,hash:'disk-hash'}};}if(cmd==='save_file'){const p=pending[args.path];disk[args.path]=p.content;return {projectId:'p1',path:args.path,clientRevision:p.clientRevision,state:'saved',diskRevision:{exists:true,hash:'saved-hash'}};}return null;}};
  w.__TAURI_EVENT_PLUGIN_INTERNALS__={unregisterListener:()=>{}};
 });
 page.on('dialog',dialog=>dialog.accept());await page.goto('/');await page.keyboard.press('Control+o');await expect(page.getByText('Native fixture',{exact:true})).toBeVisible();const f=page.frameLocator('iframe[title="Sandboxed design preview"]');await expect(f.locator('h1')).toHaveText('Disk title');await f.locator('h1').dblclick();await page.getByLabel('Canvas text edit').fill('Changed title');await page.getByLabel('Canvas text edit').press('Control+Enter');await expect(page.getByText(/Disk operation failed:/)).toBeVisible();await expect(page.getByText('Unsaved changes',{exact:true})).toBeVisible();await page.evaluate(()=>{(window as any).rejectStage=false;});await page.keyboard.press('Control+s');await expect(page.getByText('Saved to disk.',{exact:true})).toBeVisible();const calls=await page.evaluate(()=>(window as any).ipcCalls);expect(calls.find((c:any)=>c.cmd==='save_file').args.expectedRevision).toEqual({exists:true,hash:'disk-hash'});expect(calls.filter((c:any)=>c.cmd==='stage_edit').at(-1).args.content).toContain('Changed title');
});
