import {test,expect} from './fixtures';
test.use({sample:false});
test('app starts empty and offers open folder, open file and a blank page',async({page})=>{await page.setViewportSize({width:1400,height:900});await page.goto('/');
 const empty=page.getByTestId('empty-state');await expect(empty).toBeVisible();
 for(const n of ['Open folder','Open file','New blank page'])await expect(empty.getByRole('button',{name:n})).toBeVisible();
 await page.getByRole('button',{name:'Project'}).click();
 for(const n of [/Open folder/,/Open file/,/Save project/,/Export project/,/Close project/])await expect(page.getByRole('menuitem',{name:n})).toBeVisible();
 await expect(page.getByRole('menuitem',{name:/Reset to starter/})).toHaveCount(0);await expect(page.getByRole('menuitem',{name:/Compare/})).toHaveCount(0);
 await page.keyboard.press('Escape');
 await empty.getByRole('button',{name:'New blank page'}).click();await expect(empty).toBeHidden();await expect(page.getByRole('tab',{name:/index.html/}).or(page.getByText('index.html').first())).toBeVisible();});
test('open file loads a text file into a new project and export dialog lists formats',async({page})=>{await page.goto('/');
 const [chooser]=await Promise.all([page.waitForEvent('filechooser'),page.getByTestId('empty-state').getByRole('button',{name:'Open file'}).click()]);
 await chooser.setFiles({name:'hello.html',mimeType:'text/html',buffer:Buffer.from('<h1>Hello file</h1>')});
 await expect(page.getByTestId('empty-state')).toBeHidden();
 await page.keyboard.press('Control+k');await page.getByRole('combobox',{name:'Search commands'}).fill('Export project');await page.getByRole('option',{name:/Export project/}).click();
 const d=page.getByRole('dialog',{name:'Export project'});await expect(d).toBeVisible();for(const n of ['ZIP archive','Folder','Single HTML file','Markdown'])await expect(d.getByRole('radio',{name:n})).toBeVisible();
 await d.getByRole('button',{name:'Cancel'}).click();await expect(d).toBeHidden();
 await page.keyboard.press('Control+k');await page.getByRole('combobox',{name:'Search commands'}).fill('Close project');await page.getByRole('option',{name:/Close project/}).click();
 await expect(page.getByRole('dialog',{name:'Close this project?'})).toBeVisible();await page.getByRole('button',{name:'Discard and close'}).click();await expect(page.getByTestId('empty-state')).toBeVisible();});
test('dropping a text file from the file manager opens it',async({page})=>{await page.goto('/');await expect(page.getByTestId('empty-state')).toBeVisible();
 await page.evaluate(()=>{const dt=new DataTransfer();dt.items.add(new File(['<h1>Dropped</h1>'],'dropped.html',{type:'text/html'}));window.dispatchEvent(new DragEvent('dragenter',{dataTransfer:dt,bubbles:true,cancelable:true}));window.dispatchEvent(new DragEvent('drop',{dataTransfer:dt,bubbles:true,cancelable:true}));});
 await expect(page.getByTestId('empty-state')).toBeHidden();await expect(page.getByRole('status')).toContainText('dropped.html');});
