import {test,expect} from './fixtures';
import {showCode} from './helpers';
test.use({sample:false});
test('opening a Windows-1252 file keeps umlauts and declares UTF-8',async({page})=>{await page.goto('/');
 const [chooser]=await Promise.all([page.waitForEvent('filechooser'),page.getByTestId('empty-state').getByRole('button',{name:'Open file'}).click()]);
 const head=Buffer.from('<!doctype html><html><head><meta charset="iso-8859-1"><title>t</title></head><body><h1>M');
 await chooser.setFiles({name:'alt.html',mimeType:'text/html',buffer:Buffer.concat([head,Buffer.from([0xfc]),Buffer.from('ller &amp; Gr'),Buffer.from([0xf6,0xdf]),Buffer.from('e</h1></body></html>')])});
 await expect(page.getByTestId('empty-state')).toBeHidden();
 await showCode(page);const code=page.locator('.cm-content').first();
 await expect(code).toContainText('Müller & Größe'.replace('&','&amp;'));
 await expect(code).toContainText('<meta charset="UTF-8">');
 expect(await code.innerText()).not.toContain('\ufffd');
 await page.screenshot({path:'/tmp/encoding-legacy.png'});});
test('UTF-8 file with BOM opens without a stray BOM character',async({page})=>{await page.goto('/');
 const [chooser]=await Promise.all([page.waitForEvent('filechooser'),page.getByTestId('empty-state').getByRole('button',{name:'Open file'}).click()]);
 await chooser.setFiles({name:'bom.html',mimeType:'text/html',buffer:Buffer.concat([Buffer.from([0xef,0xbb,0xbf]),Buffer.from('<h1>Käse über Öl</h1>')])});
 await showCode(page);const code=page.locator('.cm-content').first();await expect(code).toContainText('Käse über Öl');
 expect(await code.innerText()).not.toContain('\ufeff');});
test('Decode special characters handles any named entity',async({page})=>{await page.goto('/');
 await page.getByTestId('empty-state').getByRole('button',{name:'New blank page'}).click();
 await showCode(page);const code=page.locator('.cm-content').first();await code.click();await page.keyboard.press('Control+a');
 await page.keyboard.insertText('&aring; &Auml; &szlig; &euro; &hearts;');await page.keyboard.press('Control+a');
 await page.keyboard.press('Control+k');await page.getByRole('combobox',{name:'Search commands'}).fill('Decode special');await page.getByRole('option',{name:/Decode special/}).click();
 await expect(code).toContainText('å Ä ß € ♥');
 await page.screenshot({path:'/tmp/encoding-decode.png'});});
