import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{page.on('pageerror',e=>console.log('PAGEERROR',e.message));page.on('console',m=>{if(m.type()==='error')console.log('CONSOLE',m.text());});});
const fixture='/tests/fixtures/extension-consent.html';
test('first-run settings is read-only until explicit Enable',async({page})=>{await page.goto(fixture+'?scenario=first');await expect(page.getByRole('heading',{name:'Extensions start paused'})).toBeVisible();expect(await page.evaluate(()=>(window as any).__consent.snapshot().acknowledged)).toBe(false);await page.getByRole('button',{name:'Keep paused',exact:true}).click();expect(await page.evaluate(()=>(window as any).__consent.snapshot().restricted)).toBe(true);await page.getByRole('button',{name:'Enable extensions',exact:true}).click();expect(await page.evaluate(()=>(window as any).__consent.snapshot().restricted)).toBe(false);});
test('restricted install says paused; Escape never grants',async({page})=>{await page.goto(fixture+'?scenario=paused');await expect(page.getByRole('button',{name:'Install, keep paused',exact:true})).toBeVisible();await page.keyboard.press('Escape');expect(await page.evaluate(()=>(window as any).__consent.commits())).toBe(0);});
test('candidate byte change fails closed',async({page})=>{await page.goto(fixture);await page.evaluate(()=>(window as any).__consent.change());await page.getByRole('button',{name:'Install and enable',exact:true}).click();await expect(page.getByRole('alert').first()).toContainText('package changed');expect(await page.evaluate(()=>(window as any).__consent.commits())).toBe(0);});
test('update decline retains old approval',async({page})=>{await page.goto(fixture+'?scenario=update');await expect(page.getByText('Version 1.3.0 is downloaded, but not running. Version 1.2.0 is still active.')).toBeVisible();await page.getByRole('button',{name:'Keep 1.2.0',exact:true}).click();expect(await page.evaluate(()=>Object.values((window as any).__consent.snapshot().extensions).map((e:any)=>[e.approved.version,e.declinedVersions]))).toEqual([['1.2.0',['1.3.0']]]);});
test('native requires uninterrupted 3 seconds; release and blur reset',async({page})=>{await page.goto(fixture+'?scenario=native');const button=page.getByRole('button',{name:'Hold for 3 seconds to install',exact:true});const box=(await button.boundingBox())!;await page.mouse.move(box.x+20,box.y+20);await page.mouse.down();await page.waitForTimeout(1000);await page.mouse.up();expect(await page.evaluate(()=>(window as any).__consent.commits())).toBe(0);await page.mouse.down();await page.waitForTimeout(500);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.waitForTimeout(3000);await page.mouse.up();expect(await page.evaluate(()=>(window as any).__consent.commits())).toBe(0);await button.focus();await page.keyboard.down('Space');await page.waitForTimeout(3300);await page.keyboard.up('Space');expect(await page.evaluate(()=>(window as any).__consent.commits())).toBe(1);});
test('runtime session selection grants nothing without action',async({page})=>{await page.goto(fixture+'?scenario=runtime');await expect(page.getByRole('radio',{name:/Allow for this session/})).toBeChecked();await expect(page.getByRole('radio',{name:/Allow always/})).toBeVisible();expect(await page.evaluate(()=>Object.values((window as any).__consent.snapshot().extensions).map((e:any)=>e.folders))).toEqual([{}]);await page.getByRole('radio',{name:/Allow always/}).check();await page.getByRole('button',{name:'Allow always',exact:true}).click();expect(await page.evaluate(()=>Object.values((window as any).__consent.snapshot().extensions).map((e:any)=>e.folders.read))).toEqual([['C:\\Users\\Philipp\\Documents\\Brand assets']]);});
test('blocklist notification retains data and has no uninstall control',async({page})=>{await page.goto(fixture+'?scenario=blocked');await page.evaluate(()=>(window as any).__consent.block());await expect(page.getByRole('heading',{name:'Disabled for safety'})).toBeVisible();await expect(page.getByText('It has not been uninstalled.',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:/uninstall/i})).toHaveCount(0);});
test('screenshots of real rendered components',async({page})=>{for(const scenario of ['install','update','first','native','runtime','blocked']){await page.goto(fixture+'?scenario='+scenario);if(scenario==='blocked')await page.evaluate(()=>(window as any).__consent.block());await page.waitForTimeout(250);await page.screenshot({path:`/downloads/consent-${scenario}.png`,fullPage:true});}await page.goto(fixture+'?scenario=update');await page.evaluate(()=>{document.documentElement.dataset.theme='dark';});await page.waitForTimeout(300);await page.screenshot({path:'/downloads/consent-dark.png'});await page.setViewportSize({width:620,height:900});await page.goto(fixture+'?scenario=install');await page.evaluate(()=>{document.querySelector<HTMLElement>('.ext-consent')!.style.setProperty('--ui-scale','2');});await page.waitForTimeout(250);await page.screenshot({path:'/downloads/consent-small.png'});});
test('native cancellation events clear host hold immediately',async({page})=>{await page.goto(fixture+'?scenario=native');const hold=page.getByRole('button',{name:'Hold for 3 seconds to install',exact:true});for(const event of ['pointercancel','lostpointercapture']){await hold.dispatchEvent('pointerdown',{button:0,pointerId:1});await page.waitForTimeout(100);await hold.dispatchEvent(event,{pointerId:1});expect(await page.evaluate(()=>(window as any).__consent.broker.nativeHoldProgress((window as any).__consent.candidate.manifest.id))).toBe(0);}await hold.focus();await page.keyboard.down('Space');await page.waitForTimeout(100);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});expect(await page.evaluate(()=>(window as any).__consent.broker.nativeHoldProgress((window as any).__consent.candidate.manifest.id))).toBe(0);await page.keyboard.up('Space');});

test('queued reviews are not silently dropped',async({page})=>{await page.goto(fixture+'?scenario=queue');await page.evaluate(()=>(window as any).__consent.queue());await expect(page.getByText('First candidate',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByText('Second candidate',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Cancel',exact:true}).click();expect(await page.evaluate(()=>(window as any).__consent.commits())).toBe(0);});
test('completed native hold survives key release during asynchronous package validation',async({page})=>{await page.goto(fixture+'?scenario=native&delay=1');const button=page.getByRole('button',{name:'Hold for 3 seconds to install',exact:true});await button.focus();await page.keyboard.down('Space');await expect(page.locator('.ext-consent [data-cancel]')).toBeDisabled({timeout:10000});expect(await page.evaluate(()=>(window as any).__consent.commits())).toBe(0);await page.keyboard.up('Space');await expect.poll(()=>page.evaluate(()=>(window as any).__consent.commits())).toBe(1);});
