import {test,expect} from './fixtures';
import path from 'node:path';
const asset=(n:string)=>path.join(import.meta.dirname,'assets',n);
async function openMedia(page:any,files:string[]){const chooser=page.waitForEvent('filechooser');await page.evaluate(async()=>{const m=await import('/src/lib/commands.ts');void m.executeCommand('project.openMedia');});(await chooser).setFiles(files.map(asset));}
const addText=(page:any,name:string,text:string)=>page.evaluate(async([n,t]:string[])=>{const m=await import('/src/lib/projectActions.ts');m.addTextFiles([{name:n,text:t}]);},[name,text]);
test('markdown file renders in the preview pane and stays safe',async({page})=>{await page.goto('/');await expect(page.locator('[data-storage]')).toBeVisible();
 await addText(page,'notes.md','# Hello Somnia\n\nSome **bold** text, a [link](https://example.com) and <script>window.__xss=1</script>\n\n- one\n- two\n\n| a | b |\n|---|---|\n| 1 | 2 |\n\n[bad](javascript:window.__xss=2)');
 const md=page.getByTestId('md-preview');await expect(md.getByRole('heading',{name:'Hello Somnia',level:1})).toBeVisible();
 await expect(md.locator('strong')).toHaveText('bold');await expect(md.locator('li')).toHaveCount(2);await expect(md.locator('td').first()).toHaveText('1');
 await expect(md.locator('script')).toHaveCount(0);await expect(md.locator('a[href^="javascript"]')).toHaveCount(0);
 await md.getByRole('link',{name:'link'}).evaluate((a:HTMLElement)=>a.addEventListener('click',e=>e.preventDefault()));
 expect(await page.evaluate(()=>(window as any).__xss)).toBeUndefined();
 await page.screenshot({path:'test-results/media-markdown.png'});});
test('svg file opens in the inline vector editor and stays safe',async({page})=>{await page.goto('/');await expect(page.locator('[data-storage]')).toBeVisible();
 await addText(page,'logo.svg','<svg xmlns="http://www.w3.org/2000/svg" width="120" height="60"><rect width="120" height="60" fill="#7c3aed"/><script>window.__xss=1</script></svg>');
 const host=page.getByTestId('svg-host');await expect(host.locator('rect')).toBeVisible();await expect(host.locator('script')).toHaveCount(0);
 await expect(page.getByTestId('svg-footer')).toContainText('120 × 60');expect(await page.evaluate(()=>(window as any).__xss)).toBeUndefined();
 await page.screenshot({path:'test-results/media-svg.png'});});
test('png opens in a preview tab, fit toggles, and text tabs still work',async({page})=>{await page.goto('/');await expect(page.locator('[data-storage]')).toBeVisible();
 await openMedia(page,['red.png']);
 const img=page.getByTestId('image-editor-stage');await expect(img).toBeVisible();await expect(page.getByTestId('media-tab')).toHaveCount(1);
 await page.screenshot({path:'test-results/media-png.png'});
 await page.getByRole('tab').first().click();await expect(page.getByTestId('image-editor-stage')).toHaveCount(0);
 await page.getByRole('button',{name:'Files'}).click();await page.getByRole('button',{name:'Preview red.png',exact:true}).click();await expect(img).toBeVisible();
 await page.getByRole('button',{name:'Close red.png'}).click();await expect(page.getByTestId('media-tab')).toHaveCount(0);});
test('pdf opens in an embedded frame and a fake png is rejected',async({page})=>{await page.goto('/');await expect(page.locator('[data-storage]')).toBeVisible();
 await openMedia(page,['doc.pdf']);await expect(page.getByTestId('pdf-frame')).toHaveAttribute('src',/^blob:/);await expect(page.getByTestId('media-name')).toHaveText('doc.pdf');
 await openMedia(page,['fake.png']);await expect(page.getByText('fake.png is not a valid PNG, JPEG, WebP or PDF file.')).toBeVisible();await expect(page.getByTestId('media-tab')).toHaveCount(1);});
test('media opens without a project (empty start)',async({page})=>{await page.addInitScript(()=>{sessionStorage.setItem('somnia.nofixture','1');});await page.goto('/');
 await openMedia(page,['red.png']);await expect(page.getByTestId('image-editor-stage')).toBeVisible();});
