import {test,expect} from './fixtures';
const key='somnia.panels.v1';
test('closed sidebars stay closed after reload and open ones stay open',async({page})=>{await page.goto('/');
 const inspector=page.getByLabel('Inspector',{exact:true});
 await expect(inspector).toBeVisible();
 const state=()=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)||'null'),key);
 await page.keyboard.press('Control+b');await page.keyboard.press('Control+Alt+i');
 await expect(inspector).toHaveCount(0);
 await expect.poll(state).toEqual({sidebarOpen:false,inspectorOpen:false});
 await page.reload();await expect(page.locator('[data-storage]')).toBeVisible();
 await expect(inspector).toHaveCount(0);
 await page.keyboard.press('Control+b');
 await expect.poll(state).toEqual({sidebarOpen:true,inspectorOpen:false});
 await page.reload();await expect(page.locator('[data-storage]')).toBeVisible();
 await expect(inspector).toHaveCount(0);
 await page.keyboard.press('Control+Alt+i');await expect(inspector).toBeVisible();
 await page.reload();await expect(page.locator('[data-storage]')).toBeVisible();
 await expect(inspector).toBeVisible();expect(await state()).toEqual({sidebarOpen:true,inspectorOpen:true});});
test('corrupt stored value falls back to both panels open',async({page})=>{await page.addInitScript(k=>localStorage.setItem(k,'{nope'),key);await page.goto('/');
 await expect(page.getByLabel('Inspector',{exact:true})).toBeVisible();});
