import {test,expect} from '@playwright/test';
import {showCode} from './helpers';
test('rails replace the duplicate tab rows',async({page})=>{await page.goto('/');
 await expect(page.getByRole('tablist',{name:'Sidebar tabs'})).toHaveCount(0);await expect(page.getByRole('tablist',{name:'Inspector tabs'})).toHaveCount(0);
 await page.getByRole('button',{name:'Files panel'}).click();await expect(page.getByRole('button',{name:'Files panel'})).toHaveAttribute('aria-pressed','true');
 await page.getByRole('button',{name:'Prototype panel'}).click();await expect(page.getByRole('button',{name:'Prototype panel'})).toHaveAttribute('aria-pressed','true');});
test('wrap lines setting wraps long code lines',async({page})=>{await page.goto('/');await showCode(page);
 const long='<p>'+'word '.repeat(120)+'</p>';await page.getByLabel('Source code').fill(long);
 const scrollW=()=>page.locator('.cm-scroller').evaluate(e=>e.scrollWidth>e.clientWidth+2);
 expect(await scrollW()).toBe(true);
 await page.getByRole('button',{name:'Tools',exact:true}).click();await page.getByRole('menuitem',{name:'Settings'}).click();await page.getByRole('button',{name:'Code editor',exact:true}).click();await page.getByLabel('Wrap long lines').check();await page.keyboard.press('Escape');
 expect(await scrollW()).toBe(false);});
test('problems panel scrolls inside its box and scrollbars stay visible but slim',async({page})=>{await page.setViewportSize({width:1100,height:640});await page.goto('/');
 await page.getByRole('button',{name:'Toggle problems'}).click();const panel=page.locator('section.problems-panel');await expect(panel).toBeVisible();
 const ok=await panel.evaluate(e=>{const cs=getComputedStyle(e);return {y:cs.overflowY,x:cs.overflowX,fits:e.getBoundingClientRect().bottom<=innerHeight};});
 expect(ok.y).toBe('auto');expect(ok.x).toBe('hidden');expect(ok.fits).toBe(true);
 const sb=await page.evaluate(()=>({body:getComputedStyle(document.body).scrollbarWidth,stage:getComputedStyle(document.querySelector('.canvas-stage')!).scrollbarWidth}));
 expect(sb.body).toBe('thin');expect(sb.stage).toBe('thin');});
test('app frame radius is twice the card radius minus 5px',async({page})=>{await page.goto('/');
 const r=await page.evaluate(()=>({frame:parseFloat(getComputedStyle(document.querySelector('.app-frame')!).borderTopLeftRadius),card:parseFloat(getComputedStyle(document.querySelector('.center')!).borderTopLeftRadius)}));
 expect(r.frame).toBe(r.card*2-5);});
