import {test,expect} from './fixtures';
test('capture authentic alpha states for product video',async({page})=>{
 await page.setViewportSize({width:1920,height:1080});await page.goto('/');
 const f=page.frameLocator('iframe[title="Sandboxed design preview"]');await expect(f.locator('h1')).toBeVisible();await page.screenshot({path:'tests/artifacts/video-01-layers.png'});
 await f.locator('h1').click();await expect(page.getByLabel('Width computed',{exact:true})).toHaveValue('1120px');await page.screenshot({path:'tests/artifacts/video-04-click-select.png'});
 await page.getByRole('button',{name:'Tablet viewport',exact:true}).click();await page.getByLabel('CSS property',{exact:true}).selectOption('font-size');await page.getByLabel('CSS value',{exact:true}).fill('28px');await page.getByRole('button',{name:'Apply CSS rule',exact:true}).click();await expect(f.locator('h1')).toHaveCSS('font-size','28px');await page.screenshot({path:'tests/artifacts/video-02-responsive-css.png'});
 await page.getByRole('button',{name:'Desktop viewport',exact:true}).click();await expect(page.getByRole('button',{name:'Desktop viewport',exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.getByLabel('Width computed',{exact:true})).toHaveValue('1120px');await f.locator('section').click({position:{x:30,y:30}});await expect(page.getByLabel('Padding computed',{exact:true})).toHaveValue('80px');await expect(page.getByLabel('Width computed',{exact:true})).toHaveValue('1120px');await page.screenshot({path:'tests/artifacts/video-03-layout.png'});await f.locator('h1').click();
 await f.locator('p').click({modifiers:['Shift']});await expect(page.getByTestId('context-chip')).toHaveText('2 selected',{timeout:20000});await page.getByLabel('CSS property',{exact:true}).selectOption('color');await page.getByLabel('CSS value',{exact:true}).fill('#225588');await page.getByRole('button',{name:'Apply CSS rule',exact:true}).click();await expect(f.locator('h1')).toHaveCSS('color','rgb(34, 85, 136)');await expect(f.locator('p')).toHaveCSS('color','rgb(34, 85, 136)');await page.screenshot({path:'tests/artifacts/video-05-multiselect.png'});
});
