import type {DesignNodeView,DesignNodePatch} from './panelContract';
import {createArtboard,uid,type DesignNode} from './model';
import {editDesign,getDesignState,selectArtboard,selectDesignNode,setDesignTool} from './session';
import type {DesignToolId} from './panelContract';
export function designRows():DesignNodeView[]{const s=getDesignState();const a=s.document?.artboards.find(a=>a.id===s.artboardId);return [...a?.nodes??[]].reverse().map(n=>({...n,type:n.kind,visible:!n.hidden,depth:0}));}
/** Applies a batch atomically, preserving locked layers and validating the full result. */
export function patchDesignNodes(patches:ReadonlyMap<string,DesignNodePatch>,allowFlags=false){const {artboardId}=getDesignState();editDesign(doc=>({...doc,artboards:doc.artboards.map(a=>a.id!==artboardId?a:{...a,nodes:a.nodes.map(n=>{const p=patches.get(n.id);if(!p||n.locked&&!allowFlags)return n;const {visible,...rest}=p;return {...n,...rest,...(visible!==undefined?{hidden:!visible}:{})};})})}));}
export function reorderDesignNode(id:string,direction:1|-1){const {artboardId}=getDesignState();editDesign(doc=>({...doc,artboards:doc.artboards.map(a=>{if(a.id!==artboardId)return a;const nodes=[...a.nodes],i=nodes.findIndex(n=>n.id===id);if(i<0||nodes[i].locked||i+direction<0||i+direction>=nodes.length)return a;[nodes[i],nodes[i+direction]]=[nodes[i+direction],nodes[i]];return {...a,nodes};})}));}
export function deleteDesignNodes(ids:readonly string[]){const {artboardId}=getDesignState();editDesign(doc=>({...doc,artboards:doc.artboards.map(a=>a.id===artboardId?{...a,nodes:a.nodes.filter(n=>!ids.includes(n.id)||n.locked)}:a)}));selectDesignNode(null);}
export function duplicateDesignNodes(ids:readonly string[]){const {artboardId}=getDesignState();editDesign(doc=>({...doc,artboards:doc.artboards.map(a=>a.id===artboardId?{...a,nodes:[...a.nodes,...a.nodes.filter(n=>ids.includes(n.id)&&!n.locked).map(n=>({...n,id:uid(),name:`${n.name} copy`,x:Math.min(32768,n.x+16),y:Math.min(32768,n.y+16)} as DesignNode))]}:a)}));}
export function chooseDesignTool(tool:DesignToolId){if(tool==='frame'){const s=getDesignState();if(!s.document||s.document.artboards.length>=100)return;const board=createArtboard(`Artboard ${s.document.artboards.length+1}`);editDesign(doc=>({...doc,artboards:[...doc.artboards,board]}));selectArtboard(board.id);setDesignTool('select');}else setDesignTool(tool);}
