import './code';
import './documents';
import './sheets';
import './slides';
import './sound';
import './video';
import './vector';
export * from './registry';
export {codeStudio} from './code';
export {documentsStudio} from './documents';
export {sheetsStudio} from './sheets';
export {slidesStudio} from './slides';
export {soundStudio} from './sound';
export {videoStudio} from './video';
export {vectorStudio} from './vector';
