import {chromium} from 'playwright';import assert from 'node:assert/strict';import {PDFDocument,StandardFonts,rgb} from 'pdf-lib';import fs from 'node:fs';import {spawn} from 'node:child_process';
const server=spawn('node',['node_modules/vite/bin/vite.js','--host','127.0.0.1'],{stdio:'ignore'});
const doc=await PDFDocument.create();const font=await doc.embedFont(StandardFonts.Helvetica);for(let i=1;i<=3;i++){const p=doc.addPage([400,500]);p.drawText(`Somnia review · Page ${i}`,{x:35,y:440,size:20,font});p.drawText('A local-first studio for creative work.',{x:35,y:390,size:12,font});p.drawRectangle({x:35,y:110,width:330,height:220,color:rgb(.28,.15,.8)});p.drawText('Prototype PDF document',{x:35,y:65,size:12,font});}const field=doc.getForm().createTextField('Reviewer');field.setText('');field.addToPage(doc.getPage(0),{x:35,y:350,width:230,height:25});const bytes=await doc.save();fs.writeFileSync('/tmp/pdf-ui-fixture.pdf',bytes);
const b=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});const page=await b.newPage({viewport:{width:1440,height:900},acceptDownloads:true});const errors=[];page.on('pageerror',e=>{errors.push(String(e));console.log('PAGEERROR',String(e));});let loaded=false;for(let i=0;i<60&&!loaded;i++){try{await page.goto('http://127.0.0.1:1420/?fallback=zip');loaded=true;}catch{await new Promise(r=>setTimeout(r,100));}}
await page.evaluate(async data=>{const {addMediaFile}=await import('/src/lib/media.ts');await addMediaFile(new Blob([new Uint8Array(data)],{type:'application/pdf'}),'brochure.pdf');},Array.from(bytes));
async function session(){return page.evaluate(async()=>{const {getPdfSession}=await import('/src/lib/pdfedit/session.ts');const s=getPdfSession('brochure.pdf');return s?{busy:s.busy,undo:s.undo.length,searching:s.searching,search:s.search,hits:s.hits,error:s.error,page:s.page}:null;});}async function until(fn){for(let i=0;i<300;i++){const s=await session();if(s&&fn(s))return s;await new Promise(r=>setTimeout(r,50));}throw Error('Session timeout '+JSON.stringify(await session()));}
await page.getByLabel('PDF viewer: brochure.pdf').waitFor();await page.locator('canvas[data-rendered=true]').waitFor();await page.getByRole('button',{name:'Fit page',exact:true}).click();await page.locator('canvas[data-rendered=true]').waitFor();await page.screenshot({path:'/downloads/pdf-inline-readonly.png'});
await page.getByRole('button',{name:'Edit PDF',exact:true}).click();await page.getByRole('button',{name:'Move page 1 down',exact:true}).click();await until(s=>s.undo===1&&!s.busy);
await page.locator('canvas[data-rendered=true]').waitFor();await page.getByRole('tab',{name:'Search',exact:true}).click();await page.getByLabel('Search PDF text').fill('Page 1');await page.getByRole('button',{name:'Find',exact:true}).click();await until(s=>s.search==='Page 1'&&!s.searching);await page.screenshot({path:'/downloads/pdf-inline-diagnostic.png'});const hits=await page.evaluate(async()=>{const {getPdfSession}=await import('/src/lib/pdfedit/session.ts');return getPdfSession('brochure.pdf').hits;});console.log('hits',hits);assert.equal(hits[0]?.page,2);
await page.getByRole('tab',{name:'Pages',exact:true}).click();await page.getByRole('button',{name:'Go to page 2',exact:true}).click();await until(s=>s.page===2);await page.getByLabel('PDF text or comment').fill('Please review the heading');await page.getByRole('button',{name:'Add annotation',exact:true}).click();await until(s=>s.undo===2&&!s.busy);
await page.locator('canvas[data-rendered=true]').waitFor();await page.getByRole('tab',{name:'Fields',exact:true}).click();await page.getByLabel('Reviewer',{exact:true}).fill('Philipp');await page.getByRole('button',{name:'Apply field values',exact:true}).click();await until(s=>s.undo===3&&!s.busy);await page.locator('canvas[data-rendered=true]').waitFor();await page.getByRole('button',{name:'Fit page',exact:true}).click();await page.screenshot({path:'/downloads/pdf-inline-fields.png'});
await page.getByRole('tab',{name:'Add',exact:true}).click();await page.getByLabel('PDF text or comment').fill('Approved for the next pass');await page.getByLabel('PDF Y position').fill('40');await page.getByRole('button',{name:'Add text',exact:true}).click();await until(s=>s.undo===4&&!s.busy);await page.locator('canvas[data-rendered=true]').waitFor();await page.getByRole('button',{name:'Fit page',exact:true}).click();await page.screenshot({path:'/downloads/pdf-inline-editing.png'});
await page.locator('canvas[data-thumbnail-rendered=true]').first().waitFor();const download=page.waitForEvent('download');await page.getByRole('button',{name:/^Save copy/}).click();await(await download).saveAs('/downloads/pdf-inline-roundtrip.pdf');await until(s=>!s.busy);const dirty=await page.evaluate(async()=>{const {getPdfSession}=await import('/src/lib/pdfedit/session.ts');return getPdfSession('brochure.pdf').dirty;});assert.equal(dirty,false);await page.evaluate(()=>window.__somnia.patch({themeChoice:'dark',theme:'dark'}));await page.locator('canvas[data-rendered=true]').waitFor();await page.screenshot({path:'/downloads/pdf-inline-dark.png'});await page.getByRole('button',{name:'Undo PDF edit',exact:true}).click();await until(s=>s.undo===3);await page.locator('canvas[data-rendered=true]').waitFor();await page.getByRole('button',{name:'Redo PDF edit',exact:true}).click();await until(s=>s.undo===4);await page.locator('canvas[data-rendered=true]').waitFor();page.once('dialog',d=>d.dismiss());await page.getByRole('button',{name:'Close brochure.pdf',exact:true}).click();assert.equal(await page.getByRole('tab',{name:/brochure.pdf/}).count(),1);await page.evaluate(async()=>{const {pdfError}=await import('/src/lib/pdfedit/session.ts');pdfError('brochure.pdf',null);});console.log('errors',errors);console.log('form', (await PDFDocument.load(fs.readFileSync('/downloads/pdf-inline-roundtrip.pdf'))).getForm().getTextField('Reviewer').getText());await b.close();server.kill();
