import {test} from 'node:test';
import assert from 'node:assert/strict';
import {EditorProject,EditorError,type EditorNode} from './index.js';
const html=`<!doctype HTML>\n<html lang='de'>\n<head><!-- leave this -->\n<style>/* exact */ .old { color : red }</style></head>\n<body>\n  <h1 id='title'>Hallo &amp; 世界</h1>\n  <p>  alpha <em>beta</em>  </p>\n  <script>const untouched = "<h1>";</script>\n</body></html>`;
const find=(p:EditorProject,tag:string)=>{let out:EditorNode|undefined;const walk=(ns:EditorNode[])=>{for(const n of ns){if(n.tag===tag)out=n;walk(n.children);}};walk(p.tree('index.html'));return out!;};
test('no-op leaves every source byte unchanged',()=>{const p=new EditorProject({'index.html':html});assert.equal(p.transact({origin:'code',operations:[{type:'replaceSource',file:'index.html',text:html}]}),null);assert.equal(p.files['index.html'],html);assert.equal(p.revision,0);});
test('text is a local escaped patch, unrelated comments/script/whitespace unchanged',()=>{const p=new EditorProject({'index.html':html});const h=find(p,'h1');p.transact({origin:'canvas',operations:[{type:'setText',file:'index.html',nodeId:h.id,text:'A < B & C'}]});assert.equal(p.files['index.html'],html.replace('Hallo &amp; 世界','A &lt; B &amp; C'));assert.equal(find(p,'h1').id,h.id);p.undo();assert.equal(p.files['index.html'],html);assert.equal(find(p,'h1').id,h.id);p.redo();assert.match(p.files['index.html'],/A &lt;/);});
test('mixed content is refused instead of flattened and transaction rolls back',()=>{const p=new EditorProject({'index.html':html});assert.throws(()=>p.transact({origin:'canvas',operations:[{type:'setText',file:'index.html',nodeId:find(p,'p').id,text:'oops'}]}),/contains markup/);assert.equal(p.files['index.html'],html);assert.equal(p.revision,0);});
test('attribute change preserves quote choice and outside bytes',()=>{const p=new EditorProject({'index.html':html});const n=find(p,'h1');p.transact({origin:'canvas',operations:[{type:'setAttribute',file:'index.html',nodeId:n.id,name:'id',value:"it's"}]});assert.equal(p.files['index.html'],html.replace("id='title'","id='it&#39;s'"));assert.equal(find(p,'h1').id,n.id);});
test('origin suppression, no-op, revision conflict',()=>{const p=new EditorProject({'index.html':html});let code=0,canvas=0;p.subscribe('code',()=>code++);p.subscribe('canvas',()=>canvas++);const n=find(p,'h1');p.transact({origin:'canvas',operations:[{type:'setText',file:'index.html',nodeId:n.id,text:'x'}]});assert.equal(code,1);assert.equal(canvas,0);assert.throws(()=>p.transact({origin:'canvas',expectedRevision:0,operations:[]}),/changed since/);assert.equal(p.revision,1);});
test('multiple operations are atomic on failure',()=>{const p=new EditorProject({'index.html':html});assert.throws(()=>p.transact({origin:'canvas',operations:[{type:'setText',file:'index.html',nodeId:find(p,'h1').id,text:'new'},{type:'remove',file:'index.html',nodeId:'missing'}]}));assert.equal(p.files['index.html'],html);assert.equal(p.canUndo,false);});
test('stable identities survive source-offset shifts and structural reorder',()=>{const p=new EditorProject({'index.html':html});const h=find(p,'h1'),em=find(p,'em'),para=find(p,'p'),body=find(p,'body');p.transact({origin:'canvas',operations:[{type:'setAttribute',file:'index.html',nodeId:h.id,name:'title',value:'long addition'}]});assert.equal(find(p,'em').id,em.id);p.transact({origin:'canvas',operations:[{type:'move',file:'index.html',nodeId:para.id,parentId:body.id,beforeId:h.id}]});assert.equal(find(p,'p').id,para.id);assert.equal(find(p,'em').id,em.id);assert.ok(find(p,'p').from<find(p,'h1').from);assert.ok(p.files['index.html'].includes('<p>  alpha <em>beta</em>  </p>'));p.undo();assert.equal(find(p,'p').id,para.id);});
test('style creates external semantic class with scoped breakpoint without !important/runtime',()=>{const p=new EditorProject({'index.html':html});const h=find(p,'h1');p.transact({origin:'canvas',operations:[{type:'setStyle',file:'index.html',nodeId:h.id,properties:{color:'#123456'},breakpoint:600}]});assert.match(p.files['somnia-styles.css'],/@media \(max-width: 600px\)/);assert.match(p.files['index.html'],/rel="stylesheet"/);assert.doesNotMatch(p.files['index.html'],/style="/);assert.doesNotMatch(p.files['somnia-styles.css'],/!important/);assert.ok(p.files['index.html'].includes("<script>const untouched = \"<h1>\";</script>"));p.undo();assert.equal(p.files['index.html'],html);assert.equal(p.files['somnia-styles.css'],undefined);});
test('lock and hide are editor-only metadata, reversible, lock protects descendants',()=>{const p=new EditorProject({'index.html':html});const para=find(p,'p'),em=find(p,'em');p.transact({origin:'canvas',operations:[{type:'setMeta',file:'index.html',nodeId:para.id,locked:true,hidden:true}]});assert.equal(p.files['index.html'],html);assert.equal(find(p,'p').hidden,true);assert.throws(()=>p.transact({origin:'canvas',operations:[{type:'setText',file:'index.html',nodeId:em.id,text:'x'}]}),/parent layer/);p.undo();assert.equal(find(p,'p').locked,false);});
test('history coalescing is shared across source and visual views',()=>{const p=new EditorProject({'index.html':html});const h=find(p,'h1');for(const text of ['a','ab','abc'])p.transact({origin:'canvas',group:'typing',operations:[{type:'setText',file:'index.html',nodeId:h.id,text}]});p.undo();assert.equal(p.files['index.html'],html);assert.equal(p.canUndo,false);});
test('unknown attributes and template syntax remain unchanged outside patch',()=>{const src='<html><head></head><body><div data-x="{{ value }}" custom-widget :foo="bar">old</div></body></html>';const p=new EditorProject({'index.html':src});p.transact({origin:'canvas',operations:[{type:'setText',file:'index.html',nodeId:find(p,'div').id,text:'new'}]});assert.equal(p.files['index.html'],src.replace('>old<','>new<'));});
test('1000 alternating edits reach stable point without echoes',()=>{const p=new EditorProject({'index.html':html});let notifications=0;p.subscribe('code',()=>notifications++);const h=find(p,'h1');for(let i=0;i<1000;i++)p.transact({origin:'canvas',operations:[{type:'setText',file:'index.html',nodeId:h.id,text:String(i)}]});assert.equal(notifications,1000);assert.equal(p.revision,1000);});
test('inline-controlled property errors rather than silently ineffective style',()=>{const src='<html><head></head><body><h1 style="color:red">x</h1></body></html>';const p=new EditorProject({'index.html':src});assert.throws(()=>p.transact({origin:'canvas',operations:[{type:'setStyle',file:'index.html',nodeId:find(p,'h1').id,properties:{color:'blue'}}]}),/inline style/);assert.equal(p.files['index.html'],src);});
test('nested HTML links project-root stylesheet with correct relative href',()=>{const p=new EditorProject({'pages/about.html':html});const walk=(ns:EditorNode[]):EditorNode=>ns.find(n=>n.tag==='h1')||ns.map(n=>{try{return walk(n.children)}catch{return undefined}}).find(Boolean)!;const n=walk(p.tree('pages/about.html'));p.transact({origin:'canvas',operations:[{type:'setStyle',file:'pages/about.html',nodeId:n.id,properties:{color:'blue'}}]});assert.match(p.files['pages/about.html'],/href="\.\.\/somnia-styles.css"/);});
test('recovery preserves stable IDs and lock metadata without leaking into output',()=>{const p=new EditorProject({'index.html':html});const h=find(p,'h1');p.transact({origin:'canvas',operations:[{type:'setMeta',file:'index.html',nodeId:h.id,locked:true}]});const q=EditorProject.fromState(JSON.parse(JSON.stringify(p.exportState())));assert.equal(find(q,'h1').id,h.id);assert.equal(find(q,'h1').locked,true);assert.equal(q.files['index.html'],html);assert.equal(q.revision,p.revision);});
test('new children insert/delete retain unrelated IDs and exact sibling source',()=>{const p=new EditorProject({'index.html':html});const h=find(p,'h1'),body=find(p,'body');const raw=p.files['index.html'];p.transact({origin:'canvas',operations:[{type:'insertHTML',file:'index.html',parentId:body.id,html:'<aside data-custom=unquoted>新</aside>',beforeId:h.id}]});assert.equal(find(p,'h1').id,h.id);p.transact({origin:'canvas',operations:[{type:'remove',file:'index.html',nodeId:find(p,'aside').id}]});assert.equal(p.files['index.html'],raw);});
test('source mutation handles CRLF and astral Unicode offsets',()=>{const src='<html>\r\n<head></head>\r\n<body>😀\r\n<h1>🪐 hello</h1>\r\n</body></html>';const p=new EditorProject({'index.html':src});p.transact({origin:'canvas',operations:[{type:'setText',file:'index.html',nodeId:find(p,'h1').id,text:'🌍 new'}]});assert.equal(p.files['index.html'],src.replace('🪐 hello','🌍 new'));});
test('subscriber cannot reenter model during propagation',()=>{const p=new EditorProject({'index.html':html});let code:string|undefined;p.subscribe('code',()=>{try{p.undo();}catch(e){code=(e as EditorError).code;}});p.transact({origin:'canvas',operations:[{type:'setText',file:'index.html',nodeId:find(p,'h1').id,text:'new'}]});assert.equal(code,'reentry');assert.equal(p.revision,1);});
test('invalid CSS and traversal stylesheet fail with exact rollback',()=>{const p=new EditorProject({'index.html':html});const id=find(p,'h1').id;for(const op of [{type:'setStyle' as const,file:'index.html',nodeId:id,properties:{color:'red; position:fixed'}},{type:'setStyle' as const,file:'index.html',nodeId:id,properties:{color:'red'},cssFile:'../outside.css'}]){assert.throws(()=>p.transact({origin:'canvas',operations:[op]}));assert.equal(p.files['index.html'],html);}});
test('range marks preserve source and entity spelling; invalid Unicode is refused',()=>{const src='<html><body><!--keep--><h1>Hello 🌙 world</h1><script>x()</script></body></html>';const p=new EditorProject({'index.html':src});const id=find(p,'h1').id;p.transact({origin:'canvas',operations:[{type:'formatText',file:'index.html',nodeId:id,from:0,to:5,mark:'strong'}]});assert.equal(p.files['index.html'],src.replace('Hello','<strong>Hello</strong>'));assert.equal(find(p,'h1').id,id);p.undo();assert.equal(p.files['index.html'],src);assert.throws(()=>p.transact({origin:'canvas',operations:[{type:'formatText',file:'index.html',nodeId:id,from:6,to:7,mark:'em'}]}),/Unicode/);assert.equal(p.files['index.html'],src);const q=new EditorProject({'index.html':html});q.transact({origin:'canvas',operations:[{type:'formatText',file:'index.html',nodeId:find(q,'h1').id,from:0,to:7,mark:'u'}]});assert.equal(q.files['index.html'],html.replace('Hallo &amp; 世界','<u>Hallo &amp;</u> 世界'));});

test('mixed inline range preserves all markup, attributes, comments and entity spelling',()=>{const src='<html><body><p>Hi <em data-x=custom>big &amp; bold</em><!--keep--> world</p></body></html>';const p=new EditorProject({'index.html':src});const id=find(p,'p').id,em=find(p,'em').id;p.transact({origin:'canvas',operations:[{type:'formatText',file:'index.html',nodeId:id,from:1,to:19,mark:'strong'}]});assert.equal(p.files['index.html'],'<html><body><p>H<strong>i </strong><em data-x=custom><strong>big &amp; bold</strong></em><!--keep--><strong> world</strong></p></body></html>');assert.equal(find(p,'em').id,em);p.undo();assert.equal(p.files['index.html'],src);});
test('unsafe block content and entity internal offset reject atomically',()=>{const src='<html><body><div>before<p>inside</p>after</div><h1>&NotEqualTilde;</h1></body></html>';const p=new EditorProject({'index.html':src});assert.throws(()=>p.transact({origin:'canvas',operations:[{type:'formatText',file:'index.html',nodeId:find(p,'div').id,from:0,to:2,mark:'em'}]}),/inline markup/);assert.throws(()=>p.transact({origin:'canvas',operations:[{type:'formatText',file:'index.html',nodeId:find(p,'h1').id,from:0,to:1,mark:'em'}]}),/entity/);assert.equal(p.files['index.html'],src);});

test('internal disk reload or reviewed merge invalidates old snapshot history',()=>{const p=new EditorProject({'index.html':html});p.transact({origin:'canvas',operations:[{type:'setText',file:'index.html',nodeId:find(p,'h1').id,text:'local'}]});assert.equal(p.canUndo,true);const external=html.replace('Hallo &amp; 世界','external');p.transact({origin:'internal',operations:[{type:'replaceSource',file:'index.html',text:external}]});assert.equal(p.canUndo,false);assert.equal(p.canRedo,false);assert.equal(p.undo(),null);assert.equal(p.files['index.html'],external);});

test('file operations create, rename, delete and undo as one history step',()=>{
 const p=new EditorProject({'index.html':'<h1>a</h1>'});
 p.transact({origin:'canvas',operations:[{type:'createFile',file:'css/site.css',text:'a{}'}]});assert.deepEqual(Object.keys(p.files).sort(),['css/site.css','index.html']);
 p.transact({origin:'canvas',operations:[{type:'renameFile',file:'css/site.css',to:'css/main.css'}]});assert.ok('css/main.css' in p.files&&!('css/site.css' in p.files));
 p.transact({origin:'canvas',operations:[{type:'deleteFile',file:'css/main.css'}]});assert.deepEqual(Object.keys(p.files),['index.html']);
 p.undo();assert.ok('css/main.css' in p.files);p.undo();assert.ok('css/site.css' in p.files);
 assert.throws(()=>p.transact({origin:'canvas',operations:[{type:'createFile',file:'INDEX.html',text:''}]}),/already exists/);
 assert.throws(()=>p.transact({origin:'canvas',operations:[{type:'createFile',file:'../x.html',text:''}]}),/not allowed|segment/);
 assert.throws(()=>p.transact({origin:'canvas',operations:[{type:'deleteFile',file:'nope.html'}]}),/not found/);
});
