import type {CodeTheme} from '../lib/appearance';
import {lazy,Suspense} from 'react';
const SourceEditor=lazy(()=>import('./SourceEditor').then(m=>({default:m.SourceEditor})));
import {DesignCanvas} from './DesignCanvas';
import { Monitor,Tablet,Smartphone,Minus,Plus } from 'lucide-react';
import { Button } from './ui/button';
import { refreshProject,patchState,useAppStore } from '../store/appStore';
import { executeCommand } from '../lib/commands';
export function Canvas(){
 const state=useAppStore();
 const code=<section className="code-pane" aria-label="Source editor"><div className="flex items-center justify-between gap-3 border-b border-subtle px-3 py-2 [&_select]:h-7 [&_select]:max-w-[65%] [&_select]:text-xs"><select aria-label="Active source file" value={state.activeFile} onChange={e=>{patchState({activeFile:e.target.value,selectedElementId:null});refreshProject();}}>{Object.keys(state.files).map(file=><option key={file}>{file}</option>)}</select><select aria-label="Code theme" title="Code color theme" value={state.codeTheme} onChange={e=>patchState({codeTheme:e.target.value as CodeTheme})}><option value="classic">Classic</option><option value="ocean">Ocean</option><option value="forest">Forest</option><option value="github">GitHub</option><option value="solarized">Solarized</option><option value="monokai">Monokai</option><option value="dracula">Dracula</option><option value="nord">Nord</option></select></div><Suspense fallback={<div className="border-t border-subtle px-3 py-2 text-[10px] text-ink-3">Loading source editor...</div>}><SourceEditor source={state.files[state.activeFile]??''} file={state.activeFile} disabled={!state.coreConnected}/></Suspense><div className="border-t border-subtle px-3 py-2 text-[10px] text-ink-3">CodeMirror source editing shares editor-core history with the canvas.</div></section>;
 return <main className="center" aria-label="Editor workspace"><div className="flex h-[52px] shrink-0 items-center gap-1 border-b border-subtle bg-transparent px-4"><div className="flex gap-0.5" aria-label="Viewport">{([{width:1280,icon:Monitor,label:'Desktop'},{width:820,icon:Tablet,label:'Tablet'},{width:390,icon:Smartphone,label:'Mobile'}] as const).map(({width,icon:Icon,label})=><Button key={width} size="compact" aria-label={`${label} viewport`} aria-pressed={state.viewport===width} onClick={()=>patchState({viewport:width})}><Icon size={15}/>{label}</Button>)}</div><span className="grow"/><Button size="icon" aria-label="Zoom out" onClick={()=>void executeCommand('zoom.out')}><Minus/></Button><label className="flex items-center [&_input]:w-11! [&_input]:border-0! [&_input]:bg-transparent! [&_input]:px-0! [&_input]:py-1! [&_input]:text-right [&_input]:[appearance:textfield] [&_input::-webkit-inner-spin-button]:hidden"><input aria-label="Zoom percent" type="number" min={25} max={200} value={state.zoom} onChange={e=>{if(e.target.value)patchState({zoom:Math.max(25,Math.min(200,Number(e.target.value)))});}}/>%</label><Button size="icon" aria-label="Zoom in" onClick={()=>void executeCommand('zoom.in')}><Plus/></Button></div><div className={`workspace workspace-${state.viewMode}`}>{state.viewMode!=='design'&&code}{state.viewMode!=='code'&&<DesignCanvas/>}</div><div className="flex h-8 shrink-0 items-center gap-2 border-t border-subtle bg-base px-4 text-[11px] text-ink-2">{state.selectedElementId?<><span>Selection</span><span> / </span><code>{state.selectedElementId}</code></>:<span>Select a layer to inspect its source. Double-click text to edit.</span>}{state.viewport!==1280&&<span className="ml-auto">Edits scoped to ≤ {state.viewport===820?900:600}px</span>}</div></main>;
}
