import {lazy,Suspense} from 'react';
const SourceEditor=lazy(()=>import('./SourceEditor').then(m=>({default:m.SourceEditor})));
import {DesignCanvas} from './DesignCanvas';
import { Monitor,Tablet,Smartphone,Minus,Plus } from 'lucide-react';
import { Button } from './ui/button';
import { refreshProject,patchState,useAppStore } from '../store/appStore';
import { executeCommand } from '../lib/commands';
export function Canvas(){
 const state=useAppStore();
 const code=<section className="code-pane" aria-label="Source editor"><div className="code-header"><select aria-label="Active source file" value={state.activeFile} onChange={e=>{patchState({activeFile:e.target.value,selectedElementId:null});refreshProject();}}>{Object.keys(state.files).map(file=><option key={file}>{file}</option>)}</select><span className="badge">CodeMirror</span></div><Suspense fallback={<div className="code-note">Loading source editor...</div>}><SourceEditor source={state.files[state.activeFile]??''} file={state.activeFile} disabled={!state.coreConnected}/></Suspense><div className="code-note">CodeMirror source editing shares editor-core history with the canvas.</div></section>;
 return <main className="center" aria-label="Editor workspace"><div className="canvas-toolbar"><div className="device-controls" aria-label="Viewport">{([{width:1280,icon:Monitor,label:'Desktop'},{width:820,icon:Tablet,label:'Tablet'},{width:390,icon:Smartphone,label:'Mobile'}] as const).map(({width,icon:Icon,label})=><Button key={width} aria-label={`${label} viewport`} aria-pressed={state.viewport===width} onClick={()=>patchState({viewport:width})}><Icon size={15}/>{label}</Button>)}</div><span className="grow"/><Button size="icon" aria-label="Zoom out" onClick={()=>void executeCommand('zoom.out')}><Minus/></Button><label className="zoom-field"><input aria-label="Zoom percent" type="number" min={25} max={200} value={state.zoom} onChange={e=>{if(e.target.value)patchState({zoom:Math.max(25,Math.min(200,Number(e.target.value)))});}}/>%</label><Button size="icon" aria-label="Zoom in" onClick={()=>void executeCommand('zoom.in')}><Plus/></Button></div><div className={`workspace workspace-${state.viewMode}`}>{state.viewMode!=='design'&&code}{state.viewMode!=='code'&&<DesignCanvas/>}</div><div className="breadcrumbs">{state.selectedElementId?<><span>Selection</span><span> / </span><code>{state.selectedElementId}</code></>:<span>Select a layer to inspect its source.</span>}</div></main>;
}
