import {useEffect,useState,type ReactNode} from 'react';
import {useT} from '../lib/useT';
import {useUiContext,getContextNode} from '../lib/uiContextStore';
import {useAppStore,patchState,applyOperations,breakpointFor} from '../store/appStore';
import {sectionsFor} from '../lib/contextRegistry';
import {ElementMetrics} from './ElementMetrics';
import {Button} from './ui/button';
import {alignSelection,distributeSelection,lockedIds} from '../lib/alignApply';
import type {Operation} from '../lib/editorPort';
const KEY='somnia.ctxSections.v1';
function readSections():Record<string,boolean>{try{return JSON.parse(localStorage.getItem(KEY)||'{}');}catch{return {};}}
export function resetContextSections(){try{localStorage.removeItem(KEY);}catch{}window.dispatchEvent(new Event('somnia:context-reset'));}
function ContextSection({id,pinned,children}:{id:string;pinned:boolean;children:ReactNode}){const c=useUiContext(),{t}=useT();const key=`${c.domain}:${c.selection.kind}:${id}`;const [prefs,setPrefs]=useState(readSections);useEffect(()=>{const run=()=>setPrefs(readSections());window.addEventListener('somnia:context-reset',run);return()=>window.removeEventListener('somnia:context-reset',run);},[]);return <details data-context-section={id} data-pinned={pinned} open={prefs[key]??(pinned||id==='advanced'||id==='computed')} onToggle={e=>{const open=e.currentTarget.open;if(open===(prefs[key]??(pinned||id==='advanced'||id==='computed')))return;const next={...prefs,[key]:open};setPrefs(next);try{localStorage.setItem(KEY,JSON.stringify(next));}catch{}}} className="border-b border-subtle"><summary role="button" className="cursor-pointer px-4 py-3 text-xs font-medium">{t('ctx.section.'+id)}</summary><div className="space-y-2 px-4 pb-3 text-xs [&_input]:w-full [&_select]:w-full">{children}</div></details>;}
export function ContextSections(){const c=useUiContext(),s=useAppStore(),{t}=useT(),node=getContextNode(c.nodeId);
 const frame=()=>document.querySelector<HTMLIFrameElement>('.design-iframe');
 const run=(ops:Operation[])=>{if(c.flags.readonly)return;try{applyOperations(ops,'canvas',`ctx:${Date.now()}`);}catch(error){patchState({notice:String(error)});}};
 const ids=s.selectedElementIds.length?s.selectedElementIds:node?[node.id]:[];
 const applyStyle=(property:string,value:string)=>{if(c.flags.locked&&c.selection.kind!=='multi')return;const locked=lockedIds(s.nodes);const available=ids.filter(id=>!locked.has(id));run(available.map(nodeId=>({type:'setStyle',file:s.designFile,nodeId,properties:{[property]:value},breakpoint:breakpointFor(s.viewport)})));if(available.length!==ids.length)patchState({notice:t('ctx.lockedSkipped')});};
 const computed=(property:string)=>{if(c.selection.kind!=='multi')return s.computedStyle[property]??'';const doc=frame()?.contentDocument;const values=ids.map(id=>{const el=doc?.querySelector(`[data-editor-node="${id}"]`);return el?doc?.defaultView?.getComputedStyle(el).getPropertyValue(property):'';});return values.every(v=>v===values[0])?values[0]??'':t('ctx.mixed');};
 const field=(name:string,label=name)=>node&&<AttributeField key={`${node.id}:${name}`} label={label} value={node.attrs[name]??''} disabled={c.flags.locked} onApply={value=>run([{type:'setAttribute',file:s.designFile,nodeId:node.id,name,value:value||null}])}/>;
 const styles=(properties:string[],readonly=false)=><>{properties.map(property=><StyleField key={`${c.nodeId}:${property}`} label={readonly?t('panels.inspector.computed',{label:t('panels.inspector.field.'+({'position':'Position','display':'Display','padding':'Padding','width':'Width','height':'Height','margin':'Margin','color':'Color','background-color':'Fill','border':'Border','border-radius':'Radius','font-family':'Font','font-size':'Size','font-weight':'Weight','line-height':'Line height','opacity':'Opacity','box-shadow':'Shadow'} as Record<string,string>)[property])}):property} value={computed(property)} disabled={readonly||c.flags.locked&&c.selection.kind!=='multi'} onApply={value=>applyStyle(property,value)}/>)}</>;
 const content=(id:string):ReactNode=>{switch(id){
 case 'page':return <><label>{t('status.viewport')}<input type="number" min={200} max={3840} value={s.viewport} onChange={e=>patchState({viewport:Math.min(3840,Math.max(200,+e.target.value))})}/></label><p>{s.activeFile}</p><p>{t('ctx.pageHint')}</p></>;
 case 'cursor':return <CursorSection/>;
 case 'typography':return styles(['font-family','font-size','line-height','color','text-align','font-weight']);
 case 'layout':return styles(['display','width','height','gap','padding','margin']);
 case 'style':return styles(['color','background-color','border','border-radius']);
 case 'effects':return styles(['opacity','box-shadow']);
 case 'image':return <>{field('src',t('ctx.source'))}{field('alt',t('ctx.alt'))}<label><input type="checkbox" className="!w-auto" disabled={c.flags.locked} checked={node?.attrs.alt===''} onChange={e=>node&&run([{type:'setAttribute',file:s.designFile,nodeId:node.id,name:'alt',value:e.target.checked?'':null}])}/>{t('ctx.decorative')}</label>{node?.tag==='img'&&(node.attrs.alt===undefined||node.attrs.alt!==''&&!node.attrs.alt.trim())&&<p role="alert" className="text-warning" data-testid="inspector-alt-warning">{t('ctx.altWarning')}</p>}{field('loading',t('ctx.loading'))}{styles(['object-fit','aspect-ratio'])}</>;
 case 'media':return <>{field('src',t('ctx.source'))}{field('poster')}{['controls','autoplay'].map(name=><label key={name}><input type="checkbox" className="!w-auto" disabled={c.flags.locked} checked={node?.attrs[name]!==undefined} onChange={e=>node&&run([{type:'setAttribute',file:s.designFile,nodeId:node.id,name,value:e.target.checked?'':null}])}/>{name}</label>)}</>;
 case 'form':return <>{['name','type','required','placeholder','aria-label'].map(name=>field(name))}</>;
 case 'component':return <Button variant="outline" onClick={()=>patchState({leftTab:'components',sidebarOpen:true})}>{t('panels.props.instancePropsAndSlots')}</Button>;
 case 'content':return <>{node&&<TextField key={node.id} disabled={c.flags.locked} onApply={text=>run([{type:'setText',file:s.designFile,nodeId:node.id,text}])}/>} {node?.tag==='a'&&<>{field('href')}{field('target')}</>}</>;
 case 'multi':return <><div className="flex flex-wrap gap-1">{(['left','hcenter','right','top','vmiddle','bottom'] as const).map(mode=><Button key={mode} size="tiny" onClick={()=>alignSelection(frame(),mode)} aria-label={t('ctx.align.'+mode)}>{t('ctx.align.'+mode)}</Button>)}{(['h','v'] as const).map(axis=><Button key={axis} size="tiny" disabled={ids.length<3} onClick={()=>distributeSelection(frame(),axis)}>{t('ctx.distribute.'+axis)}</Button>)}</div>{styles(['width','height','color','background-color','padding','margin'])}<CssPicker disabled={false} onApply={applyStyle}/></>;
 case 'advanced':return <>{field('id',t('panels.inspector.elementID'))}{field('class',t('panels.inspector.elementClasses'))}<CssPicker disabled={c.flags.locked} onApply={applyStyle}/>{node&&<TextField key={node.id} disabled={c.flags.locked} onApply={text=>run([{type:'setText',file:s.designFile,nodeId:node.id,text}])}/>}</>;
 case 'computed':return <>{node&&<ElementMetrics node={node} version={s.nodes}/>}<p>{t('panels.inspector.computedValuesBelowAreRead')}</p>{styles(['position','display','width','height','margin','padding','color','background-color','border','border-radius','font-family','font-size','font-weight','line-height','opacity','box-shadow'],true)}</>;
 }};
 return <>{['raster','vector','pdf'].includes(c.domain)&&<p className="p-4 text-xs text-ink-2">{t('ctx.nativeUnavailable')}</p>}{c.flags.locked&&<div className="border-b border-subtle p-3 text-xs" role="status">{t('ctx.locked')} <Button size="tiny" onClick={()=>{const locked=lockedIds(s.nodes);const ancestors=new Set<string>();const walk=(nodes:typeof s.nodes,path:string[])=>nodes.forEach(n=>{if(n.id===node?.id)path.concat(n.id).forEach(id=>{if(locked.has(id))ancestors.add(id);});walk(n.children,path.concat(n.id));});walk(s.nodes,[]);run([...ancestors].map(nodeId=>({type:'setMeta',file:s.designFile,nodeId,locked:false})));}}>{t('ctx.unlock')}</Button></div>}{sectionsFor(c).map(section=>section.when(c)==='grey'?<div key={section.id} className="border-b border-subtle px-4 py-3 text-xs text-ink-3" aria-disabled="true">{t('ctx.section.'+section.id)} · {t(section.greyReason??'ctx.unavailable')}</div>:<ContextSection key={`${c.domain}:${c.selection.kind}:${section.id}`} id={section.id} pinned={section.when(c)==='pin'}>{content(section.id)}</ContextSection>)}</>;
}
function AttributeField({label,value,disabled,onApply}:{label:string;value:string;disabled:boolean;onApply:(value:string)=>void}){const [draft,setDraft]=useState(value);useEffect(()=>setDraft(value),[value]);return <label className="block">{label}<input aria-label={label} disabled={disabled} value={draft} onChange={e=>setDraft(e.target.value)} onBlur={()=>{if(draft!==value)onApply(draft);}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/></label>;}
function StyleField(props:Parameters<typeof AttributeField>[0]){return <AttributeField {...props}/>;}
function TextField({disabled,onApply}:{disabled:boolean;onApply:(value:string)=>void}){const {t}=useT(),[text,setText]=useState('');return <><label className="block">{t('panels.inspector.replaceTextContent')}<input aria-label={t('panels.inspector.replacementText')} value={text} disabled={disabled} onChange={e=>setText(e.target.value)}/></label><Button variant="outline" disabled={disabled} onClick={()=>{onApply(text);setText('');}}>{t('panels.inspector.applyText')}</Button><p className="text-ink-3">{t('panels.inspector.textReplacementIsLeafOnly')}</p></>;}
function CssPicker({disabled,onApply}:{disabled:boolean;onApply:(key:string,value:string)=>void}){const {t}=useT(),[property,setProperty]=useState('color'),[value,setValue]=useState('#6366f1');return <><label>CSS<select aria-label={t('panels.inspector.cssProperty')} value={property} onChange={e=>setProperty(e.target.value)}>{['color','background-color','width','height','padding','margin','display','font-size','border-radius'].map(p=><option key={p}>{p}</option>)}</select></label><label>{t('panels.inspector.value')}<input aria-label={t('panels.inspector.cssValue')} disabled={disabled} value={value} onChange={e=>setValue(e.target.value)}/></label>{property.includes('color')&&<input aria-label={t('panels.inspector.colorPicker')} type="color" disabled={disabled} value={/^#[0-9a-f]{6}$/i.test(value)?value:'#6366f1'} onChange={e=>setValue(e.target.value)}/>}<Button variant="outline" disabled={disabled} onClick={()=>onApply(property,value)}>{t('panels.inspector.applyCSSRule')}</Button></>;}
export function CursorSection(){const c=useUiContext(),s=useAppStore(),{t}=useT();const node=getContextNode(c.nodeId);const rows:typeof s.nodes=[];const walk=(nodes:typeof s.nodes)=>nodes.forEach(n=>{rows.push(n);walk(n.children);});if(c.domain==='web')walk(s.nodes);return <div className="space-y-2 text-xs"><p>{t('status.lineCol',{line:s.cursorLine,col:s.cursorCol})} {node&&`<${node.tag}>`}</p><Button size="tiny" disabled={!node} onClick={()=>patchState({selectedElementId:node!.id,viewMode:'split'})}>{t('ctx.selectCanvas')}</Button><h4>{t('ctx.outline')}</h4><ul className="max-h-48 overflow-auto">{rows.map(n=><li key={n.id}><button className={n.id===node?.id?'text-accent':''} onClick={()=>{const source=s.files[s.designFile]??'';const before=source.slice(0,n.from);patchState({jumpTo:{file:s.designFile,line:before.split('\n').length,col:before.length-(before.lastIndexOf('\n')+1)+1,nonce:Date.now()},selectedElementId:n.id});}}>{`<${n.tag}>`}</button></li>)}</ul><h4>{t('ctx.snippets')}</h4><p>{t('ctx.emmetHint')}</p></div>;}
