import {insertElement} from '../lib/structureCommands';
import {useEffect,useMemo,useRef,useState} from 'react';
import {applyOperations,getState,patchState,useAppStore} from '../store/appStore';
import {renderPreview} from '../lib/renderPreview';
import type {EditorNode} from '../lib/editorPort';
import {CanvasContextMenu,type CanvasMenuState} from './CanvasContextMenu';
export function DesignCanvas(){
 const s=useAppStore(),stage=useRef<HTMLElement>(null),[available,setAvailable]=useState(900),ref=useRef<HTMLIFrameElement>(null);const [rect,setRect]=useState<{x:number;y:number;w:number;h:number}|null>(null);const [otherRects,setOtherRects]=useState<Array<{id:string;x:number;y:number;w:number;h:number}>>([]);const [textRange,setTextRange]=useState({from:0,to:0});const [editing,setEditing]=useState<{id:string;text:string}|null>(null);const [menu,setMenu]=useState<CanvasMenuState|null>(null);
 const scale=Math.min(s.zoom/100,Math.max(0.15,(available-64)/s.viewport));
 useEffect(()=>{if(!stage.current)return;const ro=new ResizeObserver(entries=>setAvailable(entries[0].contentRect.width));ro.observe(stage.current);return()=>ro.disconnect();},[]);
 const flat:EditorNode[]=[];const walk=(ns:EditorNode[])=>ns.forEach(n=>{flat.push(n);walk(n.children);});walk(s.nodes);const selected=flat.find(n=>n.id===s.selectedElementId);
 const src=useMemo(()=>/\.html?$/i.test(s.activeFile)?renderPreview(s.files[s.activeFile]||'',s.nodes,s.files,s.activeFile):'', [s.files,s.nodes,s.activeFile]);
 const measure=()=>{setOtherRects(getState().selectedElementIds.filter(id=>id!==getState().selectedElementId).flatMap(id=>{const target=ref.current?.contentDocument?.querySelector(`[data-editor-node="${id}"]`);if(!target)return [];const r=target.getBoundingClientRect();return [{id,x:r.x,y:r.y,w:r.width,h:r.height}];}));const el=ref.current?.contentDocument?.querySelector(`[data-editor-node="${getState().selectedElementId}"]`);if(!el){setRect(null);if(Object.keys(getState().computedStyle).length)patchState({computedStyle:{}});return;}const cs=ref.current!.contentWindow!.getComputedStyle(el);const computedStyle=Object.fromEntries(['position','display','width','height','margin','padding','color','background-color','border','border-radius','font-family','font-size','font-weight','line-height','opacity','box-shadow'].map(k=>[k,cs.getPropertyValue(k)]));if(JSON.stringify(computedStyle)!==JSON.stringify(getState().computedStyle))patchState({computedStyle});const r=el.getBoundingClientRect();setRect({x:r.x,y:r.y,w:r.width,h:r.height});};
 const bind=()=>{const doc=ref.current?.contentDocument;if(!doc)return;doc.addEventListener('contextmenu',e=>{e.preventDefault();const t=(e.target as Element).closest('[data-editor-node]');const id=t?.getAttribute('data-editor-node');if(!id){setMenu(null);return;}const box=ref.current!.getBoundingClientRect();patchState({selectedElementId:id,selectedElementIds:[id]});setMenu({id,x:Math.min(box.x+e.clientX*(box.width/ref.current!.offsetWidth),window.innerWidth-240),y:Math.min(box.y+e.clientY*(box.height/ref.current!.offsetHeight),window.innerHeight-200)});},true);doc.addEventListener('click',e=>{e.preventDefault();const t=(e.target as Element).closest('[data-editor-node]');if(t){const id=t.getAttribute('data-editor-node')!;const ids=e.shiftKey?Array.from(new Set([...getState().selectedElementIds,id])):[id];patchState({selectedElementId:id,selectedElementIds:ids});}},true);doc.addEventListener('dblclick',e=>{e.preventDefault();const t=(e.target as Element).closest('[data-editor-node]');const id=t?.getAttribute('data-editor-node');if(!id)return;const current:EditorNode[]=[];const gather=(ns:EditorNode[])=>ns.forEach(n=>{current.push(n);gather(n.children);});gather(getState().nodes);const n=current.find(n=>n.id===id);let parentLocked=false;const lockedPath=(ns:EditorNode[],locked=false):boolean=>ns.some(node=>node.id===id?(parentLocked=locked||node.locked,true):lockedPath(node.children,locked||node.locked));lockedPath(getState().nodes);if(n&&!parentLocked&&!['script','style','textarea','title'].includes(n.tag)){patchState({selectedElementId:id});setEditing({id,text:t?.textContent||''});}});doc.addEventListener('dragover',e=>{if(e.dataTransfer?.types.includes('application/x-somnia-element')){e.preventDefault();e.dataTransfer.dropEffect='copy';}});doc.addEventListener('drop',e=>{e.preventDefault();const raw=e.dataTransfer?.getData('application/x-somnia-element');if(raw==null||!/^\d+$/.test(raw))return;const target=(e.target as Element).closest('[data-editor-node]');try{insertElement(Number(raw),target?.getAttribute('data-editor-node')??null);}catch(error){patchState({notice:String(error)});}});doc.addEventListener('submit',e=>e.preventDefault());doc.addEventListener('scroll',measure,true);measure();};
 useEffect(()=>{measure();},[s.selectedElementId,s.selectedElementIds,s.zoom,s.viewport,s.revision,s.computedStyle]);
 const resizeStart=(e:React.PointerEvent<HTMLButtonElement>,kind:'size'|'padding')=>{if(!rect||!selected||selected.locked)return;e.preventDefault();const button=e.currentTarget;button.setPointerCapture(e.pointerId);const start={x:e.clientX,y:e.clientY,w:rect.w,h:rect.h};const element=ref.current?.contentDocument?.querySelector(`[data-editor-node="${selected.id}"]`);const initialPadding=element?parseFloat(ref.current!.contentWindow!.getComputedStyle(element).paddingTop)||0:0;const currentIds=s.selectedElementIds.length?s.selectedElementIds:[selected.id];const sizes=new Map(currentIds.map(id=>{const el=ref.current?.contentDocument?.querySelector(`[data-editor-node="${id}"]`);const bounds=el?.getBoundingClientRect();return [id,{w:bounds?.width??start.w,h:bounds?.height??start.h,padding:el?parseFloat(ref.current!.contentWindow!.getComputedStyle(el).paddingTop)||0:initialPadding}];}));let dx=0,dy=0;const move=(ev:PointerEvent)=>{dx=(ev.clientX-start.x)/scale;dy=(ev.clientY-start.y)/scale;if(kind==='size')setRect({...rect,w:Math.max(1,start.w+dx),h:Math.max(1,start.h+dy)});};const cancel=()=>{button.removeEventListener('pointermove',move);button.removeEventListener('pointerup',up);button.removeEventListener('pointercancel',cancel);measure();};const up=()=>{cancel();try{applyOperations(currentIds.map(id=>({type:'setStyle' as const,file:s.activeFile,nodeId:id,properties:kind==='size'?{width:`${Math.round(Math.max(1,(sizes.get(id)?.w??start.w)+dx))}px`,height:`${Math.round(Math.max(1,(sizes.get(id)?.h??start.h)+dy))}px`, 'box-sizing':'border-box'}:{padding:`${Math.round(Math.max(0,(sizes.get(id)?.padding??initialPadding)+dy))}px`} as Record<string,string>,breakpoint:s.viewport===1280?undefined:s.viewport===820?900:600})));}catch(error){patchState({notice:String(error)});measure();}};button.addEventListener('pointermove',move);button.addEventListener('pointerup',up);button.addEventListener('pointercancel',cancel);};
 const finish=(cancel=false)=>{if(!editing)return;if(!cancel&&editing.text!==ref.current?.contentDocument?.querySelector(`[data-editor-node="${editing.id}"]`)?.textContent)try{applyOperations([{type:'setText',file:s.activeFile,nodeId:editing.id,text:editing.text}]);}catch(e){patchState({notice:String(e)});}setEditing(null);};
 if(!/\.html?$/i.test(s.activeFile))return <div className="canvas-placeholder"><p>Select an HTML file for design view.</p></div>;
 const menuNode=menu?flat.find(n=>n.id===menu.id):undefined;
 return <section ref={stage} className="canvas-stage" aria-label="Design canvas"><div className="artboard-label">{s.activeFile} <span>{s.viewport} px · fit {Math.round(scale*100)}% · {s.viewport===1280?'Base styles':`Edits scoped to ≤ ${s.viewport===820?900:600}px`}</span></div><div style={{width:s.viewport*scale,height:900*scale,position:'relative'}}><div style={{width:s.viewport,height:900,position:'absolute',transform:`scale(${scale})`,transformOrigin:'top left'}}><iframe ref={ref} title="Sandboxed design preview" className="design-iframe" sandbox="allow-same-origin" srcDoc={src} onLoad={bind}/>{otherRects.map(r=><div key={r.id} className="selection-box secondary-selection" style={{left:r.x,top:r.y,width:r.w,height:r.h,pointerEvents:'none'}}/>)}{rect&&<div className="selection-box" style={{left:rect.x,top:rect.y,width:rect.w,height:rect.h,pointerEvents:'none'}}><span className="selection-label">{selected?.tag} · {Math.round(rect.w)} × {Math.round(rect.h)}</span>{!selected?.locked&&<><button aria-label="Resize selection" className="resize-selection" style={{pointerEvents:'auto'}} onPointerDown={e=>resizeStart(e,'size')}/><button aria-label="Drag padding" className="padding-selection" style={{pointerEvents:'auto'}} onPointerDown={e=>resizeStart(e,'padding')}>padding</button></>}</div>}{editing&&rect&&<><div className="richtext-toolbar" style={{left:rect.x,top:Math.max(0,rect.y-32)}}>{(['strong','em','u'] as const).map(mark=><button key={mark} aria-label={`Format ${mark}`} onMouseDown={e=>e.preventDefault()} onClick={()=>{try{const current=ref.current?.contentDocument?.querySelector(`[data-editor-node="${editing.id}"]`)?.textContent;if(editing.text!==current)throw Error('Finish text editing before formatting.');applyOperations([{type:'formatText',file:s.activeFile,nodeId:editing.id,from:textRange.from,to:textRange.to,mark}]);setEditing(null);}catch(error){patchState({notice:String(error)});}}}>{mark==='strong'?'B':mark==='em'?'I':'U'}</button>)}</div><textarea autoFocus className="text-overlay" aria-label="Canvas text edit" style={{left:rect.x,top:rect.y,width:Math.max(150,rect.w),height:Math.max(50,rect.h)}} onSelect={e=>setTextRange({from:e.currentTarget.selectionStart,to:e.currentTarget.selectionEnd})} value={editing.text} onChange={e=>setEditing({...editing,text:e.target.value})} onBlur={()=>finish()} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();finish(true);}if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();finish();}}}/></>}</div></div><div className="canvas-note">Double-click text to edit or format. Mixed markup can be formatted; text replacement is leaf-only. Scripts and remote resources are disabled in design preview.</div>{menu&&<CanvasContextMenu menu={menu} node={menuNode} onClose={()=>setMenu(null)}/>}</section>;
}
