import { useState } from 'react';
import { ChevronDown,ChevronRight,Eye,EyeOff,Lock,Unlock,Layers,Image,Component,Search } from 'lucide-react';
import { Tabs,TabsList,TabsTrigger,TabsContent } from './ui/tabs';
import { Button } from './ui/button';
import { applyOperations,patchState,useAppStore } from '../store/appStore';
import type { EditorNode } from '../lib/editorPort';
export function LayersPanel(){
 const state=useAppStore();const [query,setQuery]=useState('');const [closed,setClosed]=useState(new Set<string>());
 const matches=(node:EditorNode):boolean=>`${node.tag} ${node.attrs.id??''} ${node.attrs.class??''}`.toLowerCase().includes(query.toLowerCase())||node.children.some(matches);
 const toggleMeta=(node:EditorNode,key:'locked'|'hidden')=>{try{applyOperations([{type:'setMeta',file:state.activeFile,nodeId:node.id,[key]:!node[key]}]);}catch(error){patchState({notice:String(error)});}};
 const render=(nodes:EditorNode[],depth=0)=>nodes.filter(matches).map(node=><div key={node.id}><div className={`layer-row ${state.selectedElementIds.includes(node.id)?'selected':''}`} style={{paddingLeft:12+depth*16}}><Button size="icon" aria-label={`${closed.has(node.id)?'Expand':'Collapse'} ${node.tag}`} disabled={!node.children.length} onClick={()=>setClosed(prev=>{const next=new Set(prev);next.has(node.id)?next.delete(node.id):next.add(node.id);return next;})}>{node.children.length?(closed.has(node.id)?<ChevronRight/>:<ChevronDown/>):<span className="layer-leaf">·</span>}</Button><button className="layer-select grow" aria-label={node.tag} onClick={e=>patchState({selectedElementId:node.id,selectedElementIds:e.shiftKey?Array.from(new Set([...state.selectedElementIds,node.id])):[node.id]})} aria-pressed={state.selectedElementId===node.id}><span className="tag-icon">{node.tag.startsWith('h')?'T':'◇'}</span>{node.tag}<span className="layer-name">{node.attrs.id?`#${node.attrs.id}`:''}</span></button><Button size="icon" className="layer-action" disabled={!state.coreConnected} aria-label={`${node.hidden?'Show':'Hide'} ${node.tag}`} onClick={()=>toggleMeta(node,'hidden')}>{node.hidden?<EyeOff/>:<Eye/>}</Button><Button size="icon" className="layer-action" disabled={!state.coreConnected} aria-label={`${node.locked?'Unlock':'Lock'} ${node.tag}`} onClick={()=>toggleMeta(node,'locked')}>{node.locked?<Lock/>:<Unlock/>}</Button></div>{(!closed.has(node.id)||query)&&render(node.children,depth+1)}</div>);
 return <aside className="panel sidebar" aria-label="Project sidebar"><Tabs value={state.leftTab} onValueChange={value=>patchState({leftTab:value as typeof state.leftTab})}><TabsList aria-label="Sidebar tabs"><TabsTrigger value="layers">Layers</TabsTrigger><TabsTrigger value="assets">Assets</TabsTrigger><TabsTrigger value="components">Components</TabsTrigger></TabsList><TabsContent value="layers"><label className="search-field"><Search size={14}/><input aria-label="Filter layers" placeholder="Filter layers..." value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="panel-subtitle"><Layers size={14}/>{state.activeFile}<span className="muted grow"/>{!state.coreConnected&&<span className="badge">Demo</span>}</div><div className="layer-tree">{render(state.nodes)}{!state.nodes.some(matches)&&<p className="empty">No matching layers.</p>}</div><p className="panel-hint">{state.coreConnected?'Structure from source. Visibility and locks are editor metadata.':'Sample hierarchy only. Connect editor core to edit.'}</p></TabsContent><TabsContent value="assets"><EmptyPanel icon={<Image size={28}/>} title="Your asset library" description="Image importing is not connected yet."/></TabsContent><TabsContent value="components"><EmptyPanel icon={<Component size={28}/>} title="Reusable components" description="Component creation is not connected yet."/></TabsContent></Tabs></aside>;
}
function EmptyPanel({icon,title,description}:{icon:React.ReactNode;title:string;description:string}){return <div className="empty-panel"><div className="dropzone">{icon}<h3>{title}</h3><p>{description}</p><span className="badge">Planned integration</span></div></div>;}
