import type {ReactNode} from 'react';
import {ContextMenu} from '@base-ui/react/context-menu';
import type {EditorNode} from '../lib/editorPort';
import {applyOperations,patchState,useAppStore} from '../store/appStore';
import {moveLayer,duplicateLayer,deleteLayer} from '../lib/structureCommands';
export function LayerContextMenu({node,children}:{node:EditorNode;children:ReactNode}){
 const s=useAppStore();
 const run=(action:()=>void)=>{try{action();}catch(error){patchState({notice:error instanceof Error?error.message:String(error)});}};
 const meta=(key:'locked'|'hidden')=>run(()=>{applyOperations([{type:'setMeta',file:s.activeFile,nodeId:node.id,[key]:!node[key]}]);});
 return <ContextMenu.Root><ContextMenu.Trigger className="layer-context-trigger" onContextMenu={()=>patchState({selectedElementId:node.id})}>{children}</ContextMenu.Trigger><ContextMenu.Portal><ContextMenu.Positioner><ContextMenu.Popup className="menu-popup" aria-label={`${node.tag} layer actions`}><ContextMenu.Item className="menu-item" onClick={()=>patchState({selectedElementId:node.id,rightTab:'design'})}>Inspect {node.tag}</ContextMenu.Item><ContextMenu.Item className="menu-item" onClick={()=>patchState({selectedElementId:node.id,viewMode:'split'})}>View source</ContextMenu.Item><ContextMenu.Item className="menu-item" disabled={!s.coreConnected||node.locked} onClick={()=>run(()=>moveLayer(node.id,-1))}>Move up</ContextMenu.Item><ContextMenu.Item className="menu-item" disabled={!s.coreConnected||node.locked} onClick={()=>run(()=>moveLayer(node.id,1))}>Move down</ContextMenu.Item><ContextMenu.Item className="menu-item" disabled={!s.coreConnected||node.locked} onClick={()=>run(()=>duplicateLayer(node.id))}>Duplicate</ContextMenu.Item><ContextMenu.Item className="menu-item" disabled={!s.coreConnected||node.locked} onClick={()=>run(()=>deleteLayer(node.id))}>Delete</ContextMenu.Item><ContextMenu.Item className="menu-item" disabled={!s.coreConnected} onClick={()=>meta('hidden')}>{node.hidden?'Show layer':'Hide layer'}</ContextMenu.Item><ContextMenu.Item className="menu-item" disabled={!s.coreConnected} onClick={()=>meta('locked')}>{node.locked?'Unlock layer':'Lock layer'}</ContextMenu.Item></ContextMenu.Popup></ContextMenu.Positioner></ContextMenu.Portal></ContextMenu.Root>;
}
