import {useEffect,useMemo,useRef,useState} from 'react';
import {jumpToLine,patchState,useAppStore} from '../store/appStore';
import {Button} from './ui/button';
import {buildPreview} from '../lib/livePreview';
import {mapPreviewErrorLocation,type PreviewSourceLocation} from '../lib/previewErrorLocation';
const key=(name:string)=>`somnia.preview.scripts.${name}`;
const read=(name:string):boolean|null=>{try{const v=localStorage.getItem(key(name));return v==null?null:v==='1';}catch{return null;}};
/** Opt-in live preview. Scripts only run after a one-time choice per project; the iframe has an opaque origin and no network. */
export function LivePreview(){
 const s=useAppStore();const [allow,setAllow]=useState<boolean|null>(()=>read(s.projectName));const [auto,setAuto]=useState(true);const [tick,setTick]=useState(0);const [errors,setErrors]=useState<Array<{message:string;location:PreviewSourceLocation|null}>>([]);const [doc,setDoc]=useState('');const [blocked,setBlocked]=useState<string[]>([]);const frame=useRef<HTMLIFrameElement>(null);const scroll=useRef(0);const preview=useRef<ReturnType<typeof buildPreview>|null>(null);
 const previewFile=s.designFile||s.activeFile;const text=s.files[s.activeFile]??'';const sig=useMemo(()=>Object.keys(s.files).map(k=>k+':'+s.files[k].length+':'+s.files[k].slice(0,2000)).join('|'),[s.files]);
 useEffect(()=>{setAllow(read(s.projectName));},[s.projectName]);
 useEffect(()=>{if(allow===null)return;const run=()=>{setErrors([]);const built=buildPreview(s.files,previewFile,allow,scroll.current);preview.current=built;setBlocked(built.blocked);setDoc(built.html);};const t=window.setTimeout(run,auto?600:0);return()=>window.clearTimeout(t);},[auto?sig:'',allow,tick,previewFile]);// eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{const on=(e:MessageEvent)=>{if(e.source!==frame.current?.contentWindow)return;const d=e.data;if(!d||typeof d!=='object'||d.id!==preview.current?.id)return;if(d.somnia==='error'){const message=String(d.message).slice(0,300);const location=mapPreviewErrorLocation({message,filename:typeof d.filename==='string'?d.filename:undefined,line:d.line,col:d.col,syntax:d.syntax===true,stack:typeof d.stack==='string'?d.stack:undefined},preview.current?.scripts??[]);setErrors(x=>[...x.slice(-9),{message,location}]);}if(d.somnia==='scroll'&&typeof d.y==='number')scroll.current=d.y;};window.addEventListener('message',on);return()=>window.removeEventListener('message',on);},[]);
 const choose=(v:boolean)=>{try{localStorage.setItem(key(s.projectName),v?'1':'0');}catch{/* private mode */}setAllow(v);};
 if(allow===null)return <section className="canvas-stage grid place-items-center" aria-label="Live preview"><div className="max-w-[420px] p-6 text-center text-[13px] leading-6"><h3 className="mb-2">Run scripts in the preview?</h3><p className="mb-4 text-ink-2">The preview can run this project's own JavaScript in an isolated frame with no network access. Only allow this for projects you trust. You can change it later.</p><div className="flex justify-center gap-2"><Button onClick={()=>choose(true)}>Run scripts</Button><Button onClick={()=>choose(false)}>Preview without scripts</Button></div></div></section>;
 const scale=Math.min(1,s.zoom/100);
 return <section className="canvas-stage flex flex-col" aria-label="Live preview"><div className="flex items-center gap-2 border-b border-subtle px-3 py-1.5 text-[12px]"><span>Live preview{allow?'':' (scripts off)'}</span><span className="flex-1"/><label className="flex items-center gap-1"><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/>Auto refresh</label><Button onClick={()=>setTick(t=>t+1)} aria-label="Refresh preview">Refresh</Button><Button onClick={()=>choose(!allow)} aria-label="Toggle preview scripts">{allow?'Turn scripts off':'Turn scripts on'}</Button><Button onClick={()=>patchState({livePreview:false})} aria-label="Close live preview">Close</Button></div>
  <div className="min-h-0 flex-1 overflow-auto p-4"><div style={{width:s.viewport*scale,height:s.viewportHeight*scale}} className="mx-auto overflow-hidden rounded-[18px] border border-line bg-white shadow-sm"><iframe ref={frame} title="Live preview frame" sandbox="allow-scripts" srcDoc={doc} style={{width:s.viewport,height:s.viewportHeight,border:0,transform:`scale(${scale})`,transformOrigin:'0 0'}}/></div></div>
  {blocked.length>0&&<div role="status" aria-label="Blocked external resources" className="border-t border-line bg-amber-500/10 px-3 py-1.5 text-[11px]">The preview has no network. Blocked {blocked.length} external file{blocked.length===1?'':'s'}: {blocked.slice(0,3).join(', ')}{blocked.length>3?' …':''}. Hidden reveal-on-scroll content is shown; download the file into the project to preview its animation.</div>}
  {errors.length>0&&<div role="alert" aria-label="Preview errors" className="max-h-[30%] overflow-auto border-t border-line bg-red-500/10 px-3 py-2 font-mono text-[11px]"><div className="mb-1 flex"><strong className="flex-1">Script errors ({errors.length})</strong><button className="cursor-pointer border-0 bg-transparent text-ink-2" onClick={()=>setErrors([])}>Dismiss</button></div>{errors.map(({message,location},i)=><div key={i}>{location?<button className="cursor-pointer border-0 bg-transparent text-left text-inherit underline hover:no-underline" aria-label={`Open ${location.file} line ${location.line} column ${location.col}: ${message}`} onClick={()=>jumpToLine(location.file,location.line,location.col)}>{message} ({location.file}:{location.line}:{location.col})</button>:message}</div>)}</div>}
  <span className="sr-only" aria-live="polite">{text?'':'The file is empty.'}</span></section>;}
