import {useEffect,useState,type RefObject} from 'react';
import {useUiContext} from '../lib/uiContextStore';
import {useAppStore,applyOperations,patchState} from '../store/appStore';
import {useT} from '../lib/useT';
import {AnchoredToolbar} from './AnchoredToolbar';
import {Button} from './ui/button';
export function SelectionFormatToolbar({frame,stage,scale,suspended}:{frame:RefObject<HTMLIFrameElement|null>;stage:RefObject<HTMLElement|null>;scale:number;suspended:boolean}){const c=useUiContext(),s=useAppStore(),{t}=useT(),[rect,setRect]=useState<{x:number;y:number;w:number;h:number}|null>(null),[bounds,setBounds]=useState({w:1000,h:600});
 useEffect(()=>{const measure=()=>{const canvas=stage.current,iframe=frame.current;const element=c.nodeId?iframe?.contentDocument?.querySelector(`[data-editor-node="${c.nodeId}"]`):null;if(!canvas||!iframe||!element){setRect(null);return;}const r=element.getBoundingClientRect(),f=iframe.getBoundingClientRect(),b=canvas.getBoundingClientRect();setRect({x:f.left-b.left+r.x*scale+canvas.scrollLeft,y:f.top-b.top+r.y*scale+canvas.scrollTop,w:r.width*scale,h:r.height*scale});setBounds({w:canvas.scrollLeft+canvas.clientWidth,h:canvas.scrollTop+canvas.clientHeight});};measure();const timer=setTimeout(measure,150);stage.current?.addEventListener('scroll',measure);window.addEventListener('resize',measure);return()=>{clearTimeout(timer);stage.current?.removeEventListener('scroll',measure);window.removeEventListener('resize',measure);};},[c.nodeId,s.revision,scale]);
 if(suspended||!rect||!s.workflowPrefs.floatingFormat||c.flags.locked||c.selection.kind!=='text'||c.domain!=='web')return null;
 return <AnchoredToolbar rect={rect} bounds={bounds} selectionKey={c.nodeId??''}>{(['strong','em','u'] as const).map(mark=><Button key={mark} size="tiny" aria-label={`Format ${mark}`} onMouseDown={e=>e.preventDefault()} onClick={()=>{const element=frame.current?.contentDocument?.querySelector(`[data-editor-node="${c.nodeId}"]`);const to=element?.textContent?.length??0;if(!to)return;try{applyOperations([{type:'formatText',file:s.designFile,nodeId:c.nodeId!,from:0,to,mark}]);}catch(error){patchState({notice:String(error)});}}}>{mark==='strong'?'B':mark==='em'?'I':'U'}</Button>)}<Button size="tiny" aria-label={t('ctx.section.typography')} onClick={()=>{patchState({inspectorOpen:true,rightTab:'design'});document.querySelector<HTMLDetailsElement>('[data-context-section="typography"]')?.setAttribute('open','');}}>{t('ctx.section.typography')}</Button></AnchoredToolbar>;
}
