import test from 'node:test';
import assert from 'node:assert/strict';
import {DEFAULT_SETTINGS} from '../sound/recipe';
import type {SoundPlugin} from '../sound/protocol';
import {setSoundEngineFactory,closeSound,openSound,getSoundSession,updateSoundSettings} from '../sound/session';
import {addMediaFile,clearMedia,getMedia} from '../media';
import {createSoundStudioRegistry,parseSound,serializeSound,soundAdapter,type SoundToolHost} from './soundStudio';
import {applySound,soundFiles,undoSound} from './soundWorkspace';
import {studioFor,DocumentRegistry} from './documentCore';
const plugins:SoundPlugin[]=[{id:'plate_reverb',name:'Plate Reverb',instrument:false,offline:true,params:[{id:'mix',name:'Mix',min:0,max:100,default:30,unit:'Percent',taper:'Linear',choices:[]}]}];
const ac=()=>new AbortController().signal;
const ctx={files:()=>({}),propose:async()=>{}};
test('parseSound rejects bad shapes and out-of-range values instead of fixing them',()=>{
 assert.throws(()=>parseSound('nope'),/valid JSON/);assert.throws(()=>parseSound('[]'),/object/);
 assert.throws(()=>parseSound('{"gain":3}'),/Unknown sound setting/);
 assert.throws(()=>parseSound('{"pitch":99}'),/pitch/);assert.throws(()=>parseSound('{"pitch":"3"}'),/pitch/);
 assert.throws(()=>parseSound('{"effect":{"id":"nope","keepTail":true,"params":{}}}',plugins),/Unknown effect/);
 assert.throws(()=>parseSound('{"effect":{"id":"plate_reverb","keepTail":true,"params":{"zzz":1}}}',plugins),/no parameter/);
 assert.throws(()=>parseSound('{"effect":{"id":"plate_reverb","keepTail":true,"params":{"mix":500}}}',plugins),/out of range/);
 assert.throws(()=>parseSound('{"effect":{"id":"","keepTail":true,"params":{"mix":5}}}'),/need an effect/);
 assert.throws(()=>parseSound('{"region":{"mode":"cut","start":1,"end":9}}',[],3.5),/region/);
 assert.deepEqual(parseSound('{"pitch":3}'),{...DEFAULT_SETTINGS,pitch:3});
 assert.doesNotThrow(()=>soundAdapter.validate(serializeSound(DEFAULT_SETTINGS)));assert.throws(()=>soundAdapter.validate('{"pitch":99}'));
 assert.equal(studioFor('a.MP3'),'sound');assert.equal(studioFor('a.ogg'),'sound');assert.equal(studioFor('a.o'),'unsupported');
});
test('registry: inspect returns metadata only; propose stages a validated full settings text',async()=>{
 const docs=new DocumentRegistry([soundAdapter]);const text=serializeSound(DEFAULT_SETTINGS);docs.sync({'a.mp3':text},1);
 const staged:string[]=[];
 const host:SoundToolHost={snapshot:()=>docs.snapshot('a.mp3'),info:()=>({name:'a.mp3',duration_s:3.5,sample_rate:44100,channels:2,rendered:null}),plugins:()=>plugins,propose:a=>{staged.push(a);}};
 const r=createSoundStudioRegistry(host);
 assert.deepEqual(r.definitions().map(d=>d.name),['sound_inspect','sound_propose_settings']);assert.equal(r.level('sound_inspect'),'read');assert.equal(r.level('sound_propose_settings'),'propose');
 const info=JSON.parse(await r.run('sound_inspect',{},ctx,ac()));assert.equal(info.clip.duration_s,3.5);assert.equal(info.effects[0].params[0].id,'mix');assert.ok(!JSON.stringify(info).includes('blob:'));
 await r.run('sound_propose_settings',{settings:{pitch:5,effect:{id:'plate_reverb',keepTail:true,params:{mix:80}}}},ctx,ac());
 assert.equal(JSON.parse(staged[0]).pitch,5);assert.equal(JSON.parse(staged[0]).effect.params.mix,80);
 await assert.rejects(r.run('sound_propose_settings',{settings:{pitch:50}},ctx,ac()),/pitch/);
 await assert.rejects(r.run('sound_propose_settings',{settings:{}},ctx,ac()),/no change/);
 await assert.rejects(r.run('sound_propose_settings',{settings:{pitch:1},extra:1},ctx,ac()),/Unexpected/);
 await assert.rejects(r.run('sound_inspect',{},ctx,AbortSignal.abort()));
 assert.equal(staged.length,1);
});
test('workspace: apply goes through the session; undo only when nothing changed since',async()=>{
 const fake={async init(){return plugins;},async process(_b:ArrayBuffer,_e:string,recipe:unknown){const wav=new ArrayBuffer(44);return{wav,peaks:new Float32Array(4),report:{format:'Wav',input:{frames:100,sample_rate:44100,channels:2,duration_s:3.5,peak_db:-3,rms_db:-12},output:{frames:100,sample_rate:44100,channels:2,duration_s:3.5,peak_db:-3,rms_db:-12},trimmed_range:null,steps:[JSON.stringify(recipe)],wav_bytes:44},ms:1};},dispose(){}};
 setSoundEngineFactory(()=>fake as never);
 await addMediaFile(new File([new Uint8Array([0x49,0x44,0x33,3,0,0,0,0,0,0,...new Array(40).fill(0)])],'a.mp3',{type:'audio/mpeg'}),'a.mp3');
 const item=getMedia().items[0];await openSound(item);assert.equal(getSoundSession('a.mp3')!.status,'ready');
 assert.deepEqual(Object.keys(soundFiles()),['a.mp3']);
 const before=soundFiles()['a.mp3'];
 const next=serializeSound({...DEFAULT_SETTINGS,pitch:4});
 applySound('a.mp3',next,'ai:1');assert.equal(getSoundSession('a.mp3')!.settings.pitch,4);
 assert.throws(()=>applySound('a.mp3','{"pitch":99}','ai:2'),/pitch/);assert.equal(getSoundSession('a.mp3')!.settings.pitch,4);
 assert.throws(()=>undoSound('a.mp3','ai:other'),/later change/);
 updateSoundSettings('a.mp3',s=>({...s,reverse:true}));
 assert.throws(()=>undoSound('a.mp3','ai:1'),/Not restoring/);
 updateSoundSettings('a.mp3',s=>({...s,reverse:false}));
 undoSound('a.mp3','ai:1');assert.equal(soundFiles()['a.mp3'],before);
 closeSound('a.mp3');clearMedia();
});
