import {useState} from 'react';
import {FileTabs} from '../FileTabs';
import {useEffect} from 'react';
import {registerCommandScope} from '../../lib/commands';
import {openSlides,closeSlides,useSlidesSession} from '../../lib/slides/session';
import {Button} from '../ui/button';
export function SlidesCanvas(){const s=useSlidesSession();const [intakeError,setIntakeError]=useState('');useEffect(()=>registerCommandScope(id=>{if(id.startsWith('edit.')||id.startsWith('view.')||id.startsWith('split.')||id==='project.save')return {id,title:'Unavailable in read-only Slides preview',category:'View',enabled:()=>false,run:()=>{}};}),[]);return <main className="center flex min-h-0 flex-col overflow-hidden rounded-[var(--r-panel)] bg-panel" aria-label="Slides Studio">
 <FileTabs/><div className="flex shrink-0 items-center gap-3 border-b border-subtle px-4 py-3"><label className="cursor-pointer rounded-lg bg-hover px-3 py-2 text-sm">Open PPTX<input aria-label="Open PPTX" type="file" accept=".pptx" className="sr-only" onChange={e=>{const f=e.target.files?.[0];if(f)void openSlides(f).then(setIntakeError);e.target.value='';}}/></label><span className="min-w-0 flex-1 truncate text-sm text-ink-2">{s.name||'Slides'}</span>{s.name&&<Button variant="outline" onClick={()=>{closeSlides();setIntakeError('');}}>Close presentation</Button>}</div>
 <div className="border-b border-subtle px-4 py-2 text-xs text-ink-3">PPTX preview alpha. Read-only. Your original stays unchanged. Fonts, animations and complex objects may differ.</div>
 <div className="flex min-h-0 flex-1"><section aria-label="Slide preview" aria-busy={s.busy} className="flex min-w-0 flex-1 flex-col items-center justify-center gap-4 overflow-auto bg-shell p-6">{s.image?<img src={s.image} alt={`Slide ${s.index+1}`} className="max-h-full max-w-full object-contain shadow-sm"/>:!s.busy&&<div className="max-w-sm text-center"><h1 className="mb-3 text-xl text-ink">Open a presentation</h1><p className="text-sm text-ink-2">Preview local PowerPoint files in Somnia. Up to 200 slides and 25 MB. No cloud upload.</p></div>}{s.busy&&<p role="status" className="text-sm">Rendering presentation...</p>}{(s.error||intakeError)&&<p role="alert" className="max-w-lg rounded-lg bg-panel p-3 text-sm text-red-600">{s.error||intakeError}</p>}</section></div>
 {s.summary&&<footer className="border-t border-subtle px-4 py-2 text-xs text-ink-2">Slide {s.index+1} of {s.summary.slides} · {s.summary.widthPt} × {s.summary.heightPt} pt · Preview only</footer>}
 </main>;}
