import {unzipSync,zipSync,strFromU8,strToU8} from 'fflate';
import {listZip} from '../office/zipProbe';
export interface TextRun {slide:number;run:number;text:string;part:string}
export interface TextEdit {slide:number;run:number;old:string;text:string;part:string}
const decode=(s:string)=>s.replace(/&#x([0-9a-f]+);|&#([0-9]+);|&(amp|lt|gt|quot|apos);/gi,(_,h,d,n)=>h?String.fromCodePoint(parseInt(h,16)):d?String.fromCodePoint(parseInt(d,10)):(({amp:'&',lt:'<',gt:'>',quot:'"',apos:"'"} as Record<string,string>)[String(n).toLowerCase()]??_));
const encode=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
/** Deliberately narrow: canonical a:t tags only. Preserve every untouched uncompressed ZIP part byte-for-byte. */
const runs=/<a:t(?:\s[^>]*)?>([\s\S]*?)<\/a:t>/g;
export function readRuns(bytes:Uint8Array):TextRun[]{const entries=listZip(bytes);if(entries.length>2048||entries.some(e=>e.encrypted||e.size>16*1024*1024))throw Error('Unsupported or oversized PPTX package');if(entries.some(e=>e.name.startsWith('_xmlsignatures/')))throw Error('Digitally signed PPTX editing is not supported');const zip=unzipSync(bytes);const out:TextRun[]=[];const rels=strFromU8(zip['ppt/_rels/presentation.xml.rels']??new Uint8Array());const presentation=strFromU8(zip['ppt/presentation.xml']??new Uint8Array());const targets=new Map<string,string>();for(const m of rels.matchAll(/<Relationship\b([^>]*)\/?>/g)){const id=/\bId="([^"]+)"/.exec(m[1])?.[1],target=/\bTarget="([^"]+)"/.exec(m[1])?.[1];if(id&&target&&!/TargetMode="External"/.test(m[1]))targets.set(id,target.startsWith('/')?target.slice(1):'ppt/'+target);}
 let slide=0;for(const m of presentation.matchAll(/<p:sldId\b[^>]*r:id="([^"]+)"[^>]*\/?>/g)){const part=targets.get(m[1]);if(!part||!/^ppt\/slides\/slide\d+\.xml$/.test(part)||!zip[part])throw Error('Text editing requires canonical internal slide relationships');let run=0;for(const r of strFromU8(zip[part]).matchAll(runs))out.push({slide,run:run++,text:decode(r[1]),part});slide++;}if(!slide)throw Error('Canonical presentation slide list not found');return out;}
export function makeEditedCopy(bytes:Uint8Array,edits:readonly TextEdit[]):Uint8Array{readRuns(bytes);const zip=unzipSync(bytes);for(const edit of edits){if(new TextEncoder().encode(edit.text).length>16384||/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(edit.text)||/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/u.test(edit.text))throw Error('Text contains unsupported characters or exceeds 16 KiB');const selected=readRuns(bytes).find(r=>r.slide===edit.slide&&r.run===edit.run);if(!selected||selected.part!==edit.part)throw Error('Slide identity mismatch');const name=selected.part;if(!zip[name])throw Error('Slide XML is unavailable');let index=0,changed=false;const xml=strFromU8(zip[name]).replace(runs,(whole,inner:string)=>{if(index++!==edit.run)return whole;if(decode(inner)!==edit.old)throw Error('Text changed since selection');changed=true;return whole.replace(/(<a:t(?:\s[^>]*)?>)[\s\S]*?(<\/a:t>)/,(_m:string,open:string,close:string)=>(/\bxml:space=/.test(open)?open:open.replace(/>$/,' xml:space="preserve">'))+encode(edit.text)+close);});if(!changed)throw Error('Text run is unavailable');zip[name]=strToU8(xml);}
 return zipSync(zip,{level:6});}
