export interface CanvasPrefs{defaultViewport:number;defaultZoom:number;grid:boolean;gridSize:number;gridColor:string;selectionColor:string|null;spacingHandles:boolean;selectionWidth:number;resizeHandles:boolean;doubleClickEdit:boolean;shiftSelect:boolean;spacePan:boolean;background:string;pageShadow:'none'|'soft'|'strong'}
export const DEFAULT_CANVAS_PREFS:CanvasPrefs={defaultViewport:1280,defaultZoom:100,grid:false,gridSize:8,gridColor:'#9ca3af',selectionColor:null,spacingHandles:true,selectionWidth:2,resizeHandles:true,doubleClickEdit:true,shiftSelect:true,spacePan:true,background:'#07070b',pageShadow:'strong'};
const KEY='somnia.canvasPrefs.v1';const clamp=(v:unknown,lo:number,hi:number,d:number)=>typeof v==='number'&&Number.isFinite(v)?Math.max(lo,Math.min(hi,v)):d;const color=(v:unknown,d:string)=>typeof v==='string'&&/^#[a-f0-9]{6}$/i.test(v)?v:d;
/** null follows the theme accent. Prefs written before version 2 always stored the old default #818cf8, which silently overrode the theme, so that exact value migrates to null. */
export const LEGACY_SELECTION_COLOR='#818cf8';
export function migrateSelectionColor(x:any):string|null{const v=x?.selectionColor;if(typeof v!=='string'||!/^#[a-f0-9]{6}$/i.test(v))return null;if(x?.prefsVersion!==2&&v.toLowerCase()===LEGACY_SELECTION_COLOR)return null;return v.toLowerCase();}
export function sanitizeCanvasPrefs(x:any):CanvasPrefs{return {defaultViewport:clamp(x?.defaultViewport,200,3840,1280),defaultZoom:clamp(x?.defaultZoom,25,200,100),grid:x?.grid===true,gridSize:clamp(x?.gridSize,2,100,8),gridColor:color(x?.gridColor,'#9ca3af'),selectionColor:migrateSelectionColor(x),spacingHandles:x?.spacingHandles!==false,selectionWidth:clamp(x?.selectionWidth,1,5,2),resizeHandles:x?.resizeHandles!==false,doubleClickEdit:x?.doubleClickEdit!==false,shiftSelect:x?.shiftSelect!==false,spacePan:x?.spacePan!==false,background:color(x?.background,'#07070b'),pageShadow:x?.pageShadow==='none'||x?.pageShadow==='soft'?x.pageShadow:'strong'};}
export function readCanvasPrefs():CanvasPrefs{try{return sanitizeCanvasPrefs(JSON.parse(localStorage.getItem(KEY)||'{}'));}catch{return {...DEFAULT_CANVAS_PREFS};}}
export function saveCanvasPrefs(p:CanvasPrefs){try{localStorage.setItem(KEY,JSON.stringify({...p,prefsVersion:2}));}catch{/* session only */}}
