import {parse,serialize} from 'parse5';
export interface DocumentPrefs{font:'system'|'serif'|'monospace';fontSize:number;lineHeight:number;letterSpacing:number;paragraphSpacing:number;stripEditorIds:boolean;keepComments:boolean}
export const DEFAULT_DOCUMENT_PREFS:DocumentPrefs={font:'system',fontSize:16,lineHeight:1.5,letterSpacing:0,paragraphSpacing:1,stripEditorIds:true,keepComments:true};
export function sanitizeDocumentPrefs(x:any):DocumentPrefs{const n=(v:unknown,lo:number,hi:number,d:number)=>typeof v==='number'&&Number.isFinite(v)?Math.max(lo,Math.min(hi,v)):d;return {font:x?.font==='serif'||x?.font==='monospace'?x.font:'system',fontSize:n(x?.fontSize,8,72,16),lineHeight:n(x?.lineHeight,1,3,1.5),letterSpacing:n(x?.letterSpacing,-2,20,0),paragraphSpacing:n(x?.paragraphSpacing,0,5,1),stripEditorIds:x?.stripEditorIds!==false,keepComments:x?.keepComments!==false};}
export function readDocumentPrefs():DocumentPrefs{try{return sanitizeDocumentPrefs(JSON.parse(localStorage.getItem('somnia.documentPrefs.v1')||'{}'));}catch{return {...DEFAULT_DOCUMENT_PREFS};}}
export function saveDocumentPrefs(p:DocumentPrefs){try{localStorage.setItem('somnia.documentPrefs.v1',JSON.stringify(p));}catch{/* session only */}}
export function typographyCss(p:DocumentPrefs){const font={system:'system-ui, sans-serif',serif:'Georgia, serif',monospace:'ui-monospace, monospace'}[p.font];return `body { font-family: ${font}; font-size: ${p.fontSize}px; line-height: ${p.lineHeight}; letter-spacing: ${p.letterSpacing}px; }\np { margin-block: 0 ${p.paragraphSpacing}em; }`;}
/** Only serializes when a node actually changes; source formatting stays unchanged otherwise. */
export function cleanExportHtml(source:string,p:Pick<DocumentPrefs,'stripEditorIds'|'keepComments'>){let changed=false;const doc=parse(source);const visit=(node:any)=>{if(node.attrs&&p.stripEditorIds){const before=node.attrs.length;node.attrs=node.attrs.filter((a:any)=>a.name!=='data-somnia-id'&&a.name!=='data-editor-node');if(before!==node.attrs.length)changed=true;}if(node.childNodes){const before=node.childNodes.length;if(!p.keepComments)node.childNodes=node.childNodes.filter((n:any)=>n.nodeName!=='#comment');if(node.childNodes.length!==before)changed=true;node.childNodes.forEach(visit);}if(node.content)visit(node.content);};visit(doc);return changed?serialize(doc):source;}
