export interface BackupPrefs{enabled:boolean;count:number}
export const DEFAULT_BACKUP_PREFS:BackupPrefs={enabled:true,count:20};
export function readBackupPrefs():BackupPrefs{try{const x=JSON.parse(localStorage.getItem('somnia.backupPrefs.v1')||'{}');return {enabled:x.enabled!==false,count:typeof x.count==='number'&&Number.isFinite(x.count)?Math.max(1,Math.min(50,Math.round(x.count))):20};}catch{return {...DEFAULT_BACKUP_PREFS};}}
export function saveBackupPrefs(p:BackupPrefs){try{localStorage.setItem('somnia.backupPrefs.v1',JSON.stringify(p));}catch{/* session-only */}}
export interface ProjectBackup{id:string;name:string;files:Record<string,string>;at:string}
const KEY='somnia.projectBackups.v1',MAX=2_000_000;
const valid=(x:any):x is ProjectBackup=>x&&typeof x.id==='string'&&typeof x.name==='string'&&typeof x.at==='string'&&x.files&&typeof x.files==='object'&&!Array.isArray(x.files)&&Object.entries(x.files).every(([k,v])=>typeof v==='string'&&!k.startsWith('/')&&!k.includes('\\')&&!k.split('/').some(p=>p==='..'||p===''));
export function listProjectBackups():ProjectBackup[]{try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x.filter(valid):[];}catch{return[];}}
/** Whole-project local browser-profile snapshots, bounded by both count and bytes. Never modifies disk. */
export function saveProjectBackup(files:Readonly<Record<string,string>>,name:string,force=false):{ok:boolean;error?:string}{try{const prefs=readBackupPrefs();if(!prefs.enabled&&!force)return {ok:true};if(!Object.keys(files).length)return {ok:false,error:'No project to back up.'};const existing=listProjectBackups();if(existing[0]?.name===name&&JSON.stringify(existing[0]?.files)===JSON.stringify(files))return {ok:true};const backup={id:crypto.randomUUID(),name,files:{...files},at:new Date().toISOString()};if(!valid(backup))return {ok:false,error:'Project contains an unsafe file path.'};const list=[backup,...existing].slice(0,prefs.count);while(JSON.stringify(list).length>MAX&&list.length>1)list.pop();const text=JSON.stringify(list);if(text.length>MAX)return {ok:false,error:'Project exceeds the 2 MB local snapshot limit. Export it to a folder or ZIP instead.'};localStorage.setItem(KEY,text);window.dispatchEvent(new Event('somnia:backups-changed'));return {ok:true};}catch{return {ok:false,error:'Local backup storage is unavailable or full. Your source is unchanged.'};}}
