import {planDrop,planIndent,planOutdent,isError} from './layerDrop';
import type {DropPlan,DropZone} from './layerDrop';
import {applyOperations,getState,patchState} from '../store/appStore';
import type {EditorNode} from './editorPort';
export const elements=[{label:'Section',html:'<section>New section</section>'},{label:'Heading',html:'<h2>New heading</h2>'},{label:'Paragraph',html:'<p>New paragraph</p>'},{label:'Button',html:'<button type="button">New button</button>'},{label:'Container',html:'<div>New container</div>'},{label:'Card',html:'<article><h3>Card title</h3><p>Card description</p><a href="#">Learn more</a></article>'},{label:'Feature list',html:'<ul><li>First feature</li><li>Second feature</li><li>Third feature</li></ul>'},{label:'Hero block',html:'<section><h1>Your next idea</h1><p>A short introduction.</p><button type="button">Get started</button></section>'},{label:'FAQ block',html:'<section><h2>Questions</h2><details><summary>Your question</summary><p>Your answer.</p></details></section>'},{label:'Contact fields',html:'<form><label>Name <input name="name" autocomplete="name"></label><label>Email <input type="email" name="email" autocomplete="email"></label><button type="button">Contact</button></form>'}] as const;
export function insertElement(index:number,parentId=getState().selectedElementId){const choice=elements[index];if(!choice||!parentId)throw Error('Select a source container before inserting an element.');applyOperations([{type:'insertHTML',file:getState().designFile,parentId,html:`\n${choice.html}\n`}]);patchState({notice:`Inserted ${choice.label.toLowerCase()} into selected source container.`});}
export function moveLayer(id:string,direction:-1|1){const state=getState();let parent:EditorNode|undefined;const find=(nodes:EditorNode[])=>{for(const n of nodes){if(n.children.some(c=>c.id===id))parent=n;find(n.children);}};find(state.nodes);if(!parent)throw Error('Document roots cannot be reordered.');const i=parent.children.findIndex(n=>n.id===id);if(i+direction<0||i+direction>=parent.children.length)return;const beforeId=direction<0?parent.children[i-1].id:parent.children[i+2]?.id;applyOperations([{type:'move',file:state.designFile,nodeId:id,parentId:parent.id,beforeId}]);patchState({notice:'Moved source layer. Undo restores its previous position.'});}
function findParent(id:string){let parent:EditorNode|undefined;let self:EditorNode|undefined;const find=(nodes:EditorNode[])=>{for(const n of nodes){const c=n.children.find(x=>x.id===id);if(c){parent=n;self=c;}find(n.children);}};find(getState().nodes);return {parent,self};}
const PROTECTED=['html','head','body'];
/** Copies the element's exact source text right after itself. One undoable transaction. */
export function duplicateLayer(id:string){const state=getState();const {parent,self}=findParent(id);if(!parent||!self)throw Error('Document roots cannot be duplicated.');if(PROTECTED.includes(self.tag))throw Error('The document root cannot be duplicated.');const text=state.files[state.designFile]?.slice(self.from,self.to);if(!text)throw Error('Source for this element is not available.');const i=parent.children.findIndex(n=>n.id===id);applyOperations([{type:'insertHTML',file:state.designFile,parentId:parent.id,html:`\n${text}`,beforeId:parent.children[i+1]?.id}]);patchState({notice:'Duplicated source element. Undo removes the copy.'});}
/** Removes the element's source range. One undoable transaction. */
export function deleteLayer(id:string){const state=getState();const {self}=findParent(id);if(self&&PROTECTED.includes(self.tag))throw Error('The document root cannot be deleted.');applyOperations([{type:'remove',file:state.designFile,nodeId:id}]);patchState({selectedElementId:null,selectedElementIds:[],notice:'Deleted source element. Undo restores it.'});}

/** Applies a planned move (drag and drop, indent, outdent) as one undoable transaction. */
export function moveByPlan(id:string,plan:DropPlan,notice='Moved source layer. Undo restores its previous position.'){applyOperations([{type:'move',file:getState().designFile,nodeId:id,parentId:plan.parentId,beforeId:plan.beforeId}]);patchState({notice});}
export function dropLayer(dragId:string,targetId:string,zone:DropZone){const plan=planDrop(getState().nodes,dragId,targetId,zone);if(isError(plan)){patchState({notice:plan.error});return;}moveByPlan(dragId,plan);}
export function indentLayer(id:string){const plan=planIndent(getState().nodes,id);if(isError(plan)){patchState({notice:plan.error});return;}moveByPlan(id,plan,'Moved layer into the previous sibling. Undo restores it.');}
export function outdentLayer(id:string){const plan=planOutdent(getState().nodes,id);if(isError(plan)){patchState({notice:plan.error});return;}moveByPlan(id,plan,'Moved layer out of its parent. Undo restores it.');}

/** Wraps an element in a new container, using its exact source text. One undoable transaction. */
export function wrapLayer(id:string,tag:'div'|'section'|'article'='div'){const state=getState();const {parent,self}=findParent(id);if(!parent||!self)throw Error('Document roots cannot be wrapped.');if(PROTECTED.includes(self.tag))throw Error('The document root cannot be wrapped.');const text=state.files[state.designFile]?.slice(self.from,self.to);if(!text)throw Error('Source for this element is not available.');
 applyOperations([{type:'insertHTML',file:state.designFile,parentId:parent.id,beforeId:id,html:`<${tag}>\n${text}\n</${tag}>`},{type:'remove',file:state.designFile,nodeId:id}]);patchState({selectedElementId:null,selectedElementIds:[],notice:`Wrapped the element in a ${tag}. Undo restores it.`});}
/** Replaces an element by its own children (removes the wrapper tag, keeps the content). One undoable transaction. */
export function unwrapLayer(id:string){const state=getState();const {parent,self}=findParent(id);if(!parent||!self)throw Error('Document roots cannot be unwrapped.');if(PROTECTED.includes(self.tag))throw Error('The document root cannot be unwrapped.');if(!self.children.length)throw Error('This element has no child elements to keep. Delete it instead.');const inner=state.files[state.designFile]?.slice(self.contentFrom,self.contentTo)??'';
 applyOperations([{type:'insertHTML',file:state.designFile,parentId:parent.id,beforeId:id,html:inner.trim()},{type:'remove',file:state.designFile,nodeId:id}]);patchState({selectedElementId:null,selectedElementIds:[],notice:'Removed the wrapper and kept its content. Undo restores it.'});}
