/** Pure text operations on the source of one well-formed table. No DOM, so they run in unit tests. Nested tables and merged cells (for row/column edits) are refused instead of guessed. */
export type TableResult={html:string}|{error:string};
const ROW=/<tr\b[^>]*>[\s\S]*?<\/tr>/gi;
const CELL=/<(td|th)\b([^>]*)>([\s\S]*?)<\/\1>/gi;
interface Cell{tag:string;attrs:string;inner:string;start:number;end:number}
interface Row{start:number;end:number;cells:Cell[]}
function parse(table:string):Row[]{const rows:Row[]=[];for(const m of table.matchAll(ROW)){const rs=m.index!;const cells:Cell[]=[];for(const c of m[0].matchAll(CELL))cells.push({tag:c[1].toLowerCase(),attrs:c[2],inner:c[3],start:rs+c.index!,end:rs+c.index!+c[0].length});rows.push({start:rs,end:rs+m[0].length,cells});}return rows;}
const nested=(t:string)=>(t.match(/<table\b/gi)??[]).length>1;
const spans=(t:string)=>/\b(colspan|rowspan)\s*=/i.test(t);
const lead=(t:string,at:number)=>{let i=at;while(i>0&&/[ \t]/.test(t[i-1]))i--;return t.slice(i,at);};
const guard=(t:string,allowColspan=false):string|null=>nested(t)?'Nested tables are not supported by the table tools yet.':(!allowColspan&&spans(t))?'This table has merged cells. Row and column edits do not support merged cells yet.':/<table\b/i.test(t)?null:'Select a table first.';
const cellHtml=(tag:string)=>tag==='th'?'<th scope="col"></th>':'<td></td>';
/** Where a source offset (relative to the table start) sits: row and column index, or null. */
export function cellAt(table:string,offset:number):{row:number;col:number|null}|null{const rows=parse(table);const r=rows.findIndex(x=>offset>=x.start&&offset<x.end);if(r<0)return null;const c=rows[r].cells.findIndex(x=>offset>=x.start&&offset<x.end);return{row:r,col:c<0?null:c};}
export function tableDims(table:string){const rows=parse(table);return{rows:rows.length,cols:Math.max(0,...rows.map(r=>r.cells.length))};}
export function newTable(rows:number,cols:number,header=true):string{const r=Math.max(1,Math.min(50,rows)),c=Math.max(1,Math.min(20,cols));const th=Array.from({length:c},(_,i)=>`<th scope="col">Column ${i+1}</th>`).join('');const td=Array.from({length:c},()=>'<td></td>').join('');const body=Array.from({length:header?r-1:r},()=>`<tr>${td}</tr>`);return `<table>\n<caption>Table caption</caption>\n${header?`<thead><tr>${th}</tr></thead>\n`:''}<tbody>\n${body.join('\n')}\n</tbody>\n</table>`;}
export function addRow(table:string,row:number,after:boolean):TableResult{const e=guard(table);if(e)return{error:e};const rows=parse(table);const ref=rows[row];if(!ref)return{error:'Select a table row first.'};const n=ref.cells.length;const open=/^<tr\b[^>]*>/i.exec(table.slice(ref.start,ref.end))![0];const fresh=`${open}${Array.from({length:n},()=>'<td></td>').join('')}</tr>`;const ws=lead(table,ref.start);return{html:after?table.slice(0,ref.end)+`\n${ws}${fresh}`+table.slice(ref.end):table.slice(0,ref.start)+`${fresh}\n${ws}`+table.slice(ref.start)};}
export function deleteRow(table:string,row:number):TableResult{const e=guard(table);if(e)return{error:e};const rows=parse(table);const ref=rows[row];if(!ref)return{error:'Select a table row first.'};if(rows.length<2)return{error:'A table needs at least one row.'};let s=ref.start;while(s>0&&/\s/.test(table[s-1]))s--;return{html:table.slice(0,s)+table.slice(ref.end)};}
export function addColumn(table:string,col:number,after:boolean):TableResult{const e=guard(table);if(e)return{error:e};const rows=parse(table);if(!rows.length||rows.some(r=>!r.cells[col]))return{error:'Select a table cell first (all rows need a cell in that column).'};let out=table;for(let i=rows.length-1;i>=0;i--){const c=rows[i].cells[col];const add=cellHtml(c.tag);out=after?out.slice(0,c.end)+add+out.slice(c.end):out.slice(0,c.start)+add+out.slice(c.start);}return{html:out};}
export function deleteColumn(table:string,col:number):TableResult{const e=guard(table);if(e)return{error:e};const rows=parse(table);if(!rows.length||rows.some(r=>!r.cells[col]))return{error:'Select a table cell first (all rows need a cell in that column).'};if(Math.max(...rows.map(r=>r.cells.length))<2)return{error:'A table needs at least one column.'};let out=table;for(let i=rows.length-1;i>=0;i--){const c=rows[i].cells[col];out=out.slice(0,c.start)+out.slice(c.end);}return{html:out};}
/** Switches the first row between header cells (th, scope=col) and data cells (td). */
export function toggleHeaderRow(table:string):TableResult{const e=guard(table,true);if(e)return{error:e};const rows=parse(table);if(!rows.length)return{error:'The table has no rows.'};const first=rows[0];const toTh=first.cells.some(c=>c.tag==='td');let out=table;for(let i=first.cells.length-1;i>=0;i--){const c=first.cells[i];const attrs=c.attrs.replace(/\s*scope\s*=\s*("[^"]*"|'[^']*'|\S+)/i,'');const tag=toTh?'th':'td';out=out.slice(0,c.start)+`<${tag}${toTh?' scope="col"':''}${attrs}>${c.inner}</${tag}>`+out.slice(c.end);}return{html:out};}
/** Merges a cell with the cell to its right by colspan. Content is joined with a space. */
export function mergeRight(table:string,row:number,col:number):TableResult{const e=guard(table,true);if(e)return{error:e};if(/\browspan\s*=/i.test(table))return{error:'Tables with rowspan are not supported by the merge tool yet.'};const rows=parse(table);const r=rows[row];const a=r?.cells[col],b=r?.cells[col+1];if(!a||!b)return{error:'There is no cell to the right to merge with.'};const span=(x:Cell)=>Number(/colspan\s*=\s*["']?(\d+)/i.exec(x.attrs)?.[1]??1);const total=span(a)+span(b);const attrs=(/colspan\s*=/i.test(a.attrs)?a.attrs.replace(/colspan\s*=\s*("[^"]*"|'[^']*'|\S+)/i,`colspan="${total}"`):`${a.attrs} colspan="${total}"`);const inner=[a.inner.trim(),b.inner.trim()].filter(Boolean).join(' ');return{html:table.slice(0,a.start)+`<${a.tag}${attrs}>${inner}</${a.tag}>`+table.slice(b.end)};}
export const isTableError=(r:TableResult):r is {error:string}=>'error' in r;
