import {test} from 'node:test';import assert from 'node:assert/strict';
import {deriveContext,tagToSelectionKind} from './uiContext';import type {AppState} from '../store/appStore';import type {EditorNode} from './editorPort';import {sectionsFor,railFor,WEB_RAIL} from './contextRegistry';
const state={coreConnected:true,activeFile:'index.html',viewMode:'design',selectedElementIds:[],selectedElementId:null,viewport:1280,responsiveScope:null,isDirty:false} as unknown as AppState;
for(const [file,domain] of [['index.html','web'],['a.svg','vector'],['a.md','markdown'],['a.css','code-only'],['a.js','code-only'],['a.json','code-only'],['a.tex','code-only'],['a.ts','code-only']])test(`domain ${file}`,()=>assert.equal(deriveContext({...state,activeFile:file}).domain,domain));
for(const tag of ['h1','h2','h3','h4','h5','h6','p','span','a','li','button','label','img','picture','svg','video','audio','iframe','input','select','textarea','form','div','section','article'])for(const mode of ['design','split'] as const)test(`${mode} ${tag}`,()=>{const node={id:'n',tag,attrs:{},locked:false} as EditorNode;const ctx=deriveContext({...state,viewMode:mode,selectedElementIds:['n']},{nodes:new Map([['n',node]])});assert.equal(ctx.selection.kind,tagToSelectionKind(tag));assert.deepEqual(railFor(ctx.domain,'left'),WEB_RAIL);assert.ok(sectionsFor(ctx).length);});
test('empty and media precedence',()=>{assert.equal(deriveContext({...state,coreConnected:false}).domain,'empty');assert.equal(deriveContext({...state,coreConnected:false},{media:{name:'x.png',kind:'image'}}).domain,'raster');assert.equal(deriveContext(state,{media:{name:'x.pdf',kind:'pdf'}}).domain,'pdf');});
test('code uses cursor rather than stale canvas selection',()=>{const n={id:'cursor',tag:'p',attrs:{},locked:false} as EditorNode;assert.equal(deriveContext({...state,viewMode:'code',selectedElementIds:['old']},{cursorNode:n}).nodeId,'cursor');});
test('mixed and locked multi',()=>{const a={id:'a',tag:'h1',attrs:{},locked:false} as EditorNode,b={...a,id:'b',tag:'img',locked:true};const c=deriveContext({...state,selectedElementIds:['a','b']},{nodes:new Map([['a',a],['b',b]])});assert.deepEqual(c.selection,{kind:'multi',count:2,mixedTags:true,anyLocked:true});assert.equal(sectionsFor(c)[0].id,'multi');});
test('tool selections and flags',()=>{for(const selection of [{kind:'raster-selection',shape:'rect'},{kind:'path',anchors:5,anchorSelected:1},{kind:'pdf-text'},{kind:'vector-object',type:'text'}] as const)assert.deepEqual(deriveContext(state,{selection}).selection,selection);});
test('selection cost does not depend on 5000-node index',()=>{const nodes=new Map(Array.from({length:5000},(_,i)=>[String(i),{id:String(i),tag:'div',attrs:{},locked:false} as EditorNode]));const start=performance.now();for(let i=0;i<10000;i++)deriveContext({...state,selectedElementIds:['4999']},{nodes});assert.ok((performance.now()-start)/10000<0.2);});

test('additional raster adapters are read-only, not native RasterEditor tools',()=>{const c=deriveContext(state,{media:{name:'photo.tiff',kind:'raster-preview'}});assert.equal(c.domain,'media-readonly');assert.equal(c.flags.readonly,true);assert.equal(sectionsFor(c).some(s=>['image','layout','style'].includes(s.id)),false);});
