/**
 * Programmatic PDF fixtures for the PDF editor conformance tests.
 * Everything is generated with pdf-lib at test time: no binary files in the repo.
 * Fixtures use only Standard-14 fonts, so they need no embedded font data.
 */
import { PDFDocument, PDFName, StandardFonts, rgb } from 'pdf-lib';

export const PAGE_SIZE = { width: 612, height: 792 } as const; // US Letter, points

export interface TextFixtureOptions {
  /** One entry per page. Each string is drawn as one line of Helvetica 14pt. */
  readonly pages?: readonly (readonly string[])[];
  readonly title?: string;
}

/** Text that every default fixture page contains, per page, so tests can assert on it. */
export const DEFAULT_PAGE_TEXT: readonly (readonly string[])[] = [
  ['Somnia fixture page 1', 'Hello PDF world'],
];

async function save(doc: PDFDocument): Promise<Uint8Array> {
  // useObjectStreams:false keeps the output greppable and easy for naive parsers.
  return doc.save({ useObjectStreams: false });
}

function fixedDoc(title: string): Promise<PDFDocument> {
  return PDFDocument.create().then((doc) => {
    doc.setTitle(title);
    // Fixed dates keep generated bytes stable between runs.
    const epoch = new Date(Date.UTC(2026, 0, 1));
    doc.setCreationDate(epoch);
    doc.setModificationDate(epoch);
    doc.setProducer('somnia-test-fixtures');
    doc.setCreator('somnia-test-fixtures');
    return doc;
  });
}

/** Single or multi page document with Standard-14 Helvetica text lines. */
export async function makeTextPdf(opts: TextFixtureOptions = {}): Promise<Uint8Array> {
  const pages = opts.pages ?? DEFAULT_PAGE_TEXT;
  const doc = await fixedDoc(opts.title ?? 'Somnia text fixture');
  const font = await doc.embedFont(StandardFonts.Helvetica);
  for (const lines of pages) {
    const page = doc.addPage([PAGE_SIZE.width, PAGE_SIZE.height]);
    lines.forEach((line, i) => {
      page.drawText(line, { x: 72, y: PAGE_SIZE.height - 100 - i * 24, size: 14, font, color: rgb(0, 0, 0) });
    });
  }
  return save(doc);
}

/** Multi-page document: page N contains "Page N of COUNT" so order is checkable after reorder/delete. */
export async function makeMultiPagePdf(count = 5): Promise<Uint8Array> {
  if (!Number.isInteger(count) || count < 1 || count > 200) throw new RangeError('count must be 1..200');
  const pages = Array.from({ length: count }, (_, i) => [`Page ${i + 1} of ${count}`]);
  return makeTextPdf({ pages, title: 'Somnia multipage fixture' });
}

export const ACROFORM_FIELDS = {
  text: 'full_name',
  checkbox: 'accept_terms',
  dropdown: 'country',
  radio: 'plan',
} as const;
export const ACROFORM_DROPDOWN_OPTIONS = ['Germany', 'France', 'Spain'] as const;
export const ACROFORM_RADIO_OPTIONS = ['free', 'pro'] as const;

/** One page with a text field, checkbox, dropdown and radio group (an AcroForm). */
export async function makeAcroFormPdf(): Promise<Uint8Array> {
  const doc = await fixedDoc('Somnia acroform fixture');
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const page = doc.addPage([PAGE_SIZE.width, PAGE_SIZE.height]);
  const form = doc.getForm();
  const label = (text: string, y: number) => page.drawText(text, { x: 72, y: y + 4, size: 12, font });

  label('Name', 700);
  const name = form.createTextField(ACROFORM_FIELDS.text);
  name.setText('Ada Lovelace');
  name.addToPage(page, { x: 160, y: 692, width: 240, height: 24 });

  label('Accept', 650);
  const accept = form.createCheckBox(ACROFORM_FIELDS.checkbox);
  accept.addToPage(page, { x: 160, y: 644, width: 18, height: 18 });

  label('Country', 600);
  const country = form.createDropdown(ACROFORM_FIELDS.dropdown);
  country.addOptions([...ACROFORM_DROPDOWN_OPTIONS]);
  country.select('Germany');
  country.addToPage(page, { x: 160, y: 592, width: 160, height: 24 });

  label('Plan', 550);
  const plan = form.createRadioGroup(ACROFORM_FIELDS.radio);
  ACROFORM_RADIO_OPTIONS.forEach((opt, i) => {
    plan.addOptionToPage(opt, page, { x: 160 + i * 60, y: 544, width: 18, height: 18 });
  });
  plan.select('free');

  form.updateFieldAppearances(font);
  return save(doc);
}

/** Cheap structural facts about a PDF, read through pdf-lib, for assertions. */
export interface PdfFacts {
  readonly pageCount: number;
  readonly fieldNames: readonly string[];
  readonly hasAcroForm: boolean;
}

export async function inspectPdf(bytes: Uint8Array): Promise<PdfFacts> {
  const doc = await PDFDocument.load(bytes, { updateMetadata: false });
  // Read hasAcroForm first: pdf-lib's getForm() creates an empty AcroForm as a side effect.
  const hasAcroForm = doc.catalog.has(PDFName.of('AcroForm'));
  const fieldNames = hasAcroForm ? doc.getForm().getFields().map((f) => f.getName()).sort() : [];
  return { pageCount: doc.getPageCount(), fieldNames, hasAcroForm };
}

/** True when the bytes start with a PDF header and end with %%EOF (ignoring trailing whitespace). */
export function looksLikePdf(bytes: Uint8Array): boolean {
  if (bytes.length < 16) return false;
  const head = new TextDecoder('latin1').decode(bytes.subarray(0, 5));
  const tail = new TextDecoder('latin1').decode(bytes.subarray(Math.max(0, bytes.length - 1024)));
  return head === '%PDF-' && /%%EOF\s*$/.test(tail);
}
