import {after,before,test} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {readFileSync} from 'node:fs';
import {chromium,type Browser,type Page} from '@playwright/test';
let browser:Browser,page:Page,server:ReturnType<typeof spawn>;const port=1439;
before(async()=>{server=spawn(process.execPath,['node_modules/vite/bin/vite.js',...(process.env.SOMNIA_PRODUCTION==='1'?['preview']:[]),'--host','127.0.0.1','--port',String(port)],{stdio:'ignore'});for(let i=0;i<120;i++){try{if((await fetch(`http://127.0.0.1:${port}`)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});page=await browser.newPage({viewport:{width:1440,height:900}});await page.addInitScript('window.__name=(fn)=>fn;localStorage.setItem("somnia.themeChoice","light");localStorage.setItem("somnia.welcome.seen.v1","11.2.0-beta.1")');await page.goto(`http://127.0.0.1:${port}`);});
after(async()=>{await browser?.close();server?.kill();});
async function open(name:string,buffer:Buffer){const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Project',exact:true}).click();await page.getByRole('menuitem',{name:'Open image or PDF to preview',exact:true}).click();await(await chooser).setFiles({name,mimeType:'image/vnd.adobe.photoshop',buffer});}
for(const compression of ['raw','rle','zip'])test(`PSD ${compression} merged preview runs real WASM and exact pixels, never editable`,async()=>{const original=readFileSync(`validation/fixtures/psd-${compression}.psd`);await open(`${compression}.psd`,original);await page.getByTestId('psd-preview').waitFor();const pixel=await page.getByTestId('psd-preview').evaluate((c:HTMLCanvasElement)=>({size:[c.width,c.height],pixel:[...c.getContext('2d')!.getImageData(40,40,1,1).data]}));assert.deepEqual(pixel,{size:[128,96],pixel:[220,45,65,255]});assert.equal(await page.getByRole('button',{name:'Save copy...',exact:true}).count(),0);assert.equal(await page.getByText('No layer records', {exact:true}).count(),1);if(compression==='zip')await page.screenshot({path:'/tmp/psd-preview-light.png'});});
test('truncated PSD reports an error without raster fallback or edits',async()=>{await open('truncated.psd',readFileSync('validation/fixtures/psd-truncated.psd'));await page.getByRole('alert').waitFor();assert.match(await page.getByRole('alert').innerText(),/end|EOF|bytes|offset/i);assert.equal(await page.getByTestId('psd-preview').isVisible(),false);});
test('PSD header bounds reject hostile dimensions before decode',async()=>{const data=readFileSync('validation/fixtures/psd-raw.psd');data.writeUInt32BE(0xffffffff,14);data.writeUInt32BE(0xffffffff,18);await open('oversize.psd',data);await page.getByRole('alert').waitFor();assert.match(await page.getByRole('alert').innerText(),/bounded/);});
test('unsupported PSB is not accepted as PSD',async()=>{const data=readFileSync('validation/fixtures/psd-raw.psd');data.writeUInt16BE(2,4);await open('unsupported.psd',data);await page.getByText(/unsupported.psd is not a valid/).waitFor();});
test('compressed oversized output remains bounded and preview is exact-length',async()=>{await open('bomb.psd',readFileSync('validation/fixtures/psd-bomb.psd'));await page.getByRole('alert').waitFor();assert.match(await page.getByRole('alert').innerText(),/decompress|size|bytes|zlib/i);});
for(const [name,pattern] of [['cmyk',/RGB/],['16bit',/8-bit/],['zero',/bounded/],['section-overrun',/exceeds file|overflow/],['many-layers',/32-layer/],['no-merged',/no real merged/]] as const)test(`PSD ${name} fails explicitly without editable conversion`,async()=>{await open(`${name}.psd`,readFileSync(`validation/fixtures/psd-${name}.psd`));await page.getByRole('alert').waitFor();assert.match(await page.getByRole('alert').innerText(),pattern);assert.equal(await page.getByTestId('psd-preview').isVisible(),false);});
test('real layered PSD reads Unicode names while still using merged pixels, tab switches retain original',async()=>{await open('layered.psd',readFileSync('validation/fixtures/psd-layers.psd'));await page.getByTestId('psd-preview').waitFor();await page.getByText('背景 / Background',{exact:true}).waitFor();await page.getByText('Hidden detail',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Save copy...',exact:true}).count(),0);await page.getByTestId('media-tab').filter({hasText:'raw.psd'}).click();await page.getByTestId('psd-preview').waitFor();await page.getByTestId('media-tab').filter({hasText:'layered.psd'}).click();await page.getByText('背景 / Background',{exact:true}).waitFor();await page.screenshot({path:'/tmp/psd-layer-metadata-light.png'});});
