import React from 'react';
import {createRoot} from 'react-dom/client';
import {ChangesTab} from '../../../src/components/versions/ChangesTab';
import {CompareTab} from '../../../src/components/versions/CompareTab';
import {setVersionsSession} from '../../../src/lib/versionsSession';
import {setLocale} from '../../../src/lib/i18n';
import '../../../src/styles/global.css';
const mode=new URLSearchParams(location.search).get('mode')||'light';
document.documentElement.dataset.theme=mode;document.documentElement.classList.toggle('dark',mode==='dark');
setLocale('en');
const handlers:Record<string,(e:any)=>void>={};
let id=0;
(window as any).__TAURI_INTERNALS__={transformCallback:(cb:any)=>{handlers[String(++id)]=cb;return id;},invoke:async(cmd:string,args:any)=>cmd==='plugin:event|listen'?args.handler:undefined};
(window as any).__TAURI_EVENT_PLUGIN_INTERNALS__={unregisterListener:()=>{}};
(window as any).isTauri=true;
setVersionsSession({projectId:'p',port:{invoke:async()=>undefined as any},nextRevision:()=>1,hasUnsavedBuffers:()=>false,settle:async()=>{},applyRecoveryRestore:async()=>{},reloadFromDisk:async()=>({changed:[]})});
let disk='Original',calls=0;const html=()=>`<html><body><h1>${disk}</h1></body></html>`;
const repo={root:'/p',projectPrefix:'',branch:'main',detached:false,unborn:false,head:'a'.repeat(40),upstream:null,ahead:0,behind:0,hasLfs:false,hasSubmodules:false,gitVersion:'2.43.0'};
const backend:any={detect:async()=>({kind:'ready',repo}),status:async()=>{calls++;return{repo,changes:[{path:disk==='Original'?'index.html':'updated.html',kind:'modified',staged:false,unstaged:true,binary:false}],stateToken:disk,truncated:false};},diff:async(path:string,base:string,target:string)=>({path,base,target,binary:false,before:'<html><body><h1>Before</h1></body></html>',after:html(),tooLarge:false})};
(window as any).invalidate=()=>{disk='Refreshed';Object.values(handlers).forEach(fn=>fn({event:'somnia://git-invalidated',payload:{projectId:'p',generation:1,watcherFailed:false}}));};
(window as any).calls=()=>calls;
createRoot(document.getElementById('root')!).render(<main style={{display:'grid',gridTemplateColumns:'340px minmax(0,1fr)',gap:24,padding:24,height:'100vh',background:'var(--bg)',color:'var(--ink)'}}><aside><ChangesTab backend={backend} unsavedFiles={0} onSaveFiles={()=>{}} advanced={false}/></aside><article><CompareTab backend={backend}/></article></main>);
