import {ImageConversionDialog} from './components/ImageConversionDialog';
import {Account} from './components/Account';
import {applyWindowBackground} from './lib/windowBackground';
import {isTauri} from '@tauri-apps/api/core';
import {getCurrentWindow} from '@tauri-apps/api/window';
import {ExtensionPanel} from './components/ExtensionPanel';
import {activateExtensions} from './lib/extensions/host';
import {loadActiveExtensions} from './lib/extensions/registry';
import logoMark from './assets/logo-mark.svg';
import {ExportDialog} from './components/ExportDialog';
import {CloseProjectDialog} from './components/CloseProjectDialog';
import {Breadcrumbs} from './components/Breadcrumbs';
import {DropOverlay} from './components/DropOverlay';
import {SaveDialog} from './components/SaveDialog';
import {ProblemsPanel} from './components/ProblemsPanel';
import { getState,patchState,breakpointFor } from './store/appStore';
import { applyLook } from './lib/look';
import { ViewportControls } from './components/ViewportControls';
import { resolveTheme } from './lib/theme';
import { cn } from './lib/cn';
import {Settings} from './components/Settings';
import {DiskComparison} from './components/DiskComparison';
import { useEffect } from 'react';
import { WindowControls } from './components/WindowControls';
import { Menu } from '@base-ui/react/menu';
import { Monitor,Tablet,Smartphone,Minus,Plus,Search,Undo2,Redo2,PanelLeft,PanelRight,Code2,Columns2,MousePointer2,ChevronsUpDown } from './lib/icons';
import { Button } from './components/ui/button';
import { Badge } from './components/ui/badge';
import { Separator } from './components/ui/separator';
import { IconRail } from './components/IconRail';
import { CommunicationPanel } from './components/CommunicationPanel';
import {ChatMentionToast} from './components/SessionChat';
import {openSessionChat} from './lib/collab/communication';
import {getChatSession} from './lib/collab/chatSession';
import { LayersPanel } from './components/LayersPanel';
import { CloseDialog } from './components/CloseDialog';
import { UpdatePill } from './components/UpdatePill';
import { ShareDialog } from './components/ShareDialog';
import { CollabStatus } from './components/CollabStatus';
import { Inspector } from './components/Inspector';
import { Canvas } from './components/Canvas';
import { CommandPalette } from './components/CommandPalette';
import { ResizeHandle } from './components/ResizeHandle';
import { attachKeyboardShortcuts,commandEnabled,executeCommand,formatShortcut,listCommands } from './lib/commands';
import { useAppStore } from './store/appStore';
import { StatusBar } from './components/StatusBar';
import {useT} from './lib/useT';
import {isMarkdown,useMedia} from './lib/media';
const card='flex shrink-0 items-center rounded-lg bg-panel shadow-card';
export function App(){
 const {t}=useT();const state=useAppStore();const media=useMedia();useEffect(()=>attachKeyboardShortcuts(),[]);useEffect(()=>{let off=activateExtensions(loadActiveExtensions());const re=()=>{off();off=activateExtensions(loadActiveExtensions());};window.addEventListener('somnia:extensions-changed',re);return()=>{window.removeEventListener('somnia:extensions-changed',re);off();};},[]);useEffect(()=>{const apply=()=>{const r=resolveTheme(state.themeChoice);document.documentElement.dataset.palette=r.palette;if(getState().theme!==r.mode)patchState({theme:r.mode});};apply();if(state.themeChoice!=='system')return;const mq=matchMedia('(prefers-color-scheme: dark)');mq.addEventListener('change',apply);return()=>mq.removeEventListener('change',apply);},[state.themeChoice]);useEffect(()=>{document.documentElement.dataset.theme=state.theme;document.documentElement.dataset.contrast=state.contrast;document.documentElement.dataset.codeTheme=state.codeTheme;},[state.theme,state.contrast,state.codeTheme]);useEffect(()=>{/* Glass depends on theme colours (code floor) and the OS transparency switch. */const re=()=>applyLook(getState().look);re();if(typeof matchMedia!=='function')return;const mq=matchMedia('(prefers-reduced-transparency: reduce)');mq.addEventListener?.('change',re);return()=>mq.removeEventListener?.('change',re);},[state.theme,state.contrast,state.codeTheme]);
 useEffect(()=>{void applyWindowBackground({mode:state.look.background,dark:state.theme==='dark',highContrast:state.contrast==='high'});},[state.look.background,state.theme,state.contrast]);
 const action=(id:string)=>void executeCommand(id);
 const mdActive=isMarkdown(state.activeFile)&&!media.active;
 const inspectorShown=state.inspectorOpen&&(!mdActive||!!state.activePanel.right);
 return <div className="app-frame flex h-dvh min-h-[600px] min-w-[960px] flex-col gap-shell bg-shell p-shell"><header className="relative -mx-shell -mt-shell flex h-11 shrink-0 items-center gap-1 border-b border-subtle bg-transparent px-3 select-none" data-tauri-drag-region onDoubleClick={e=>{if(state.windowPrefs.doubleClick==='maximize'&&isTauri()&&(e.target as HTMLElement).hasAttribute('data-tauri-drag-region'))void getCurrentWindow().toggleMaximize();}}><div className="size-7 bg-ink" style={{maskImage:`url("${logoMark}")`,maskSize:"contain",maskRepeat:"no-repeat",maskPosition:"center",WebkitMaskImage:`url("${logoMark}")`,WebkitMaskSize:"contain",WebkitMaskRepeat:"no-repeat",WebkitMaskPosition:"center"}} data-tauri-drag-region aria-hidden="true"/><span className="w-2"/><div className="flex gap-0.5">{(['Project','Edit','View','Insert','Tools','Help'] as const).map(category=><Menu.Root key={category}><Menu.Trigger className="h-8 cursor-pointer rounded-sm border-0 bg-transparent px-2.5 text-ink-2 hover:bg-hover hover:text-ink data-[popup-open]:bg-hover data-[popup-open]:text-ink">{t('menu.'+category)}</Menu.Trigger><Menu.Portal><Menu.Positioner sideOffset={4}><Menu.Popup className="menu-popup">{listCommands().filter(c=>c.category===category).map(command=><Menu.Item key={command.id} className="menu-item" disabled={!commandEnabled(command)} onClick={()=>action(command.id)}><span>{command.title}</span>{command.shortcut&&<kbd>{formatShortcut(command.shortcut)}</kbd>}</Menu.Item>)}</Menu.Popup></Menu.Positioner></Menu.Portal></Menu.Root>)}</div><Separator/><Button size="icon" aria-label={t('cmd.edit.undo')} disabled={!state.coreConnected} onClick={()=>action('edit.undo')}><Undo2/></Button><Button size="icon" aria-label={t('cmd.edit.redo')} disabled={!state.coreConnected} onClick={()=>action('edit.redo')}><Redo2/></Button><span className="grow" data-tauri-drag-region/><div className="absolute left-1/2 -translate-x-1/2 flex gap-1 rounded-[var(--r-control)] bg-hover p-1">{([{mode:'design',icon:MousePointer2},{mode:'split',icon:Columns2},{mode:'code',icon:Code2}] as const).map(({mode,icon:Icon})=><Button key={mode} size="compact" className="gap-1.5 rounded-[calc(var(--r-control)-4px)] px-3" aria-label={mdActive?t('md.view.'+mode):t('cmd.view.'+mode)} aria-pressed={state.viewMode===mode} onClick={()=>action(`view.${mode}`)}><Icon/><span className="text-[12px]">{t(mdActive?'md.view.'+mode:'finish2.toolbar.'+mode)}</span></Button>)}</div><span className="grow" data-tauri-drag-region/><Button variant="outline" className="!h-8 rounded-[var(--r-control)]" onClick={()=>action('palette.open')}><Search size={14}/><span>{t('finish2.toolbar.commands')}</span><kbd>{formatShortcut('Mod+K')}</kbd></Button><Account/><WindowControls/></header><div className="flex min-h-0 flex-1 gap-1"><IconRail side="left"/><div className="editor-layout" style={{gridTemplateColumns:`${state.sidebarOpen?`${state.sidebarWidth}px var(--gap)`:'0px 0px'} minmax(180px,1fr) ${inspectorShown?`var(--gap) ${state.inspectorWidth}px`:'0px 0px'}`}}><div className="pane-slot">{state.sidebarOpen&&(state.activePanel.left?<ExtensionPanel id={state.activePanel.left}/>:<LayersPanel/>)}</div>{state.sidebarOpen?<ResizeHandle side="left"/>:<span/>}<Canvas/>{inspectorShown?<ResizeHandle side="right"/>:<span/>}<div className="pane-slot">{inspectorShown&&(state.activePanel.right?<ExtensionPanel id={state.activePanel.right}/>:<Inspector/>)}</div></div>{state.agentOpen&&<CommunicationPanel/>}<IconRail side="right"/></div>{state.problemsOpen&&<ProblemsPanel/>}<StatusBar/><ChatMentionToast/><ChatShortcut/><CommandPalette/><Settings/><DiskComparison/><ImageConversionDialog/></div>;
}

function ChatShortcut(){useEffect(()=>{const listener=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.code==='KeyC'&&getChatSession()){e.preventDefault();openSessionChat();}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[]);return null;}
