import type { ExportLocale } from './types';
const en = {
  title:'Export PDF', preset:'Preset', print:'Print - preserve text and vectors', screen:'Screen - JPEG pages',
  printHelp:'Keeps source fonts and images. No image downsampling or PDF/X conversion.',
  screenHelp:'120 DPI / 78% JPEG by default. Removes searchable text, accessibility and links. Smaller size is not guaranteed.',
  metadata:'Document metadata', documentTitle:'Title', author:'Author', subject:'Subject', keywords:'Keywords (comma-separated)',
  dpi:'Screen DPI', quality:'JPEG quality (%)', export:'Export copy', busy:'Exporting...', cancel:'Cancel',
  flatten:'Flatten annotations and forms', flattenHelp:'Bakes visible appearances into the pages. Removes review comments and form interactivity. Not redaction.',
  standard:'Standard-14 fonts', standardHelp:'Existing fonts stay unchanged. New Latin text uses Helvetica, Times or Courier; unsupported glyphs are rejected.',
  subset:'Embed a subset font', subsetHelp:'No font embedding/shaping adapter is installed. Unicode additions need one.',
  linearize:'Fast web view (linearize)', linearizeHelp:'The current PDF writer cannot linearize files.',
  pdfx:'PDF/X or CMYK conversion', pdfxHelp:'No color-managed print conversion or PDF/X validation is installed.',
  unavailable:'Export unavailable', protected:'Encrypted, signed and XFA files are view-only.',
  renderer:'Canvas rendering is not available on this platform.', unsupported:'Some annotations have no safe appearance; export will stop rather than drop them.',
  done:'Copy ready', invalid:'Check the export settings.',
};
type Messages = typeof en;
export const exportMessages: Record<ExportLocale, Messages> = {
  en,
  de:{title:'PDF exportieren',preset:'Vorgabe',print:'Druck - Text und Vektoren erhalten',screen:'Bildschirm - JPEG-Seiten',printHelp:'Erhält Quellschriften und Bilder. Keine Bildverkleinerung oder PDF/X-Konvertierung.',screenHelp:'Standard: 120 DPI / 78 % JPEG. Entfernt durchsuchbaren Text, Barrierefreiheit und Links. Kleinere Dateien sind nicht garantiert.',metadata:'Dokumentmetadaten',documentTitle:'Titel',author:'Autor',subject:'Betreff',keywords:'Stichwörter (durch Kommas getrennt)',dpi:'Bildschirm-DPI',quality:'JPEG-Qualität (%)',export:'Kopie exportieren',busy:'Export läuft...',cancel:'Abbrechen',flatten:'Anmerkungen und Formulare reduzieren',flattenHelp:'Übernimmt sichtbare Darstellungen in die Seiten. Entfernt Kommentare und interaktive Formulare. Keine Schwärzung.',standard:'Standard-14-Schriften',standardHelp:'Vorhandene Schriften bleiben erhalten. Neuer lateinischer Text nutzt Helvetica, Times oder Courier; nicht unterstützte Zeichen werden abgelehnt.',subset:'Schrift als Untergruppe einbetten',subsetHelp:'Kein Adapter für Schrifteinbettung oder Textformung installiert. Unicode-Ergänzungen benötigen einen.',linearize:'Schnelle Webanzeige (linearisieren)',linearizeHelp:'Der aktuelle PDF-Writer kann Dateien nicht linearisieren.',pdfx:'PDF/X- oder CMYK-Konvertierung',pdfxHelp:'Keine farbverwaltete Druckkonvertierung oder PDF/X-Prüfung installiert.',unavailable:'Export nicht verfügbar',protected:'Verschlüsselte, signierte und XFA-Dateien sind schreibgeschützt.',renderer:'Canvas-Rendering ist auf dieser Plattform nicht verfügbar.',unsupported:'Einige Anmerkungen haben keine sichere Darstellung; der Export wird gestoppt, statt sie zu entfernen.',done:'Kopie bereit',invalid:'Exporteinstellungen prüfen.'},
  es:{title:'Exportar PDF',preset:'Ajuste',print:'Impresión - conservar texto y vectores',screen:'Pantalla - páginas JPEG',printHelp:'Conserva las fuentes e imágenes originales. No reduce imágenes ni convierte a PDF/X.',screenHelp:'Por defecto: 120 DPI / JPEG al 78 %. Elimina texto buscable, accesibilidad y enlaces. No garantiza un archivo menor.',metadata:'Metadatos del documento',documentTitle:'Título',author:'Autor',subject:'Asunto',keywords:'Palabras clave (separadas por comas)',dpi:'DPI de pantalla',quality:'Calidad JPEG (%)',export:'Exportar copia',busy:'Exportando...',cancel:'Cancelar',flatten:'Acoplar anotaciones y formularios',flattenHelp:'Integra las apariencias visibles en las páginas. Elimina comentarios y formularios interactivos. No es censura segura.',standard:'Fuentes Standard-14',standardHelp:'Las fuentes existentes no cambian. El texto latino nuevo usa Helvetica, Times o Courier; se rechazan caracteres incompatibles.',subset:'Incrustar un subconjunto de fuente',subsetHelp:'No hay adaptador de incrustación o composición de fuentes. Las adiciones Unicode necesitan uno.',linearize:'Vista web rápida (linealizar)',linearizeHelp:'El escritor PDF actual no puede linealizar archivos.',pdfx:'Conversión PDF/X o CMYK',pdfxHelp:'No hay conversión de impresión con gestión de color ni validación PDF/X.',unavailable:'Exportación no disponible',protected:'Los archivos cifrados, firmados y XFA son de solo lectura.',renderer:'El renderizado en canvas no está disponible en esta plataforma.',unsupported:'Algunas anotaciones no tienen una apariencia segura; se detendrá la exportación en vez de omitirlas.',done:'Copia lista',invalid:'Revisa los ajustes de exportación.'},
  fr:{title:'Exporter le PDF',preset:'Préréglage',print:'Impression - conserver texte et vecteurs',screen:'Écran - pages JPEG',printHelp:'Conserve les polices et images sources. Aucune réduction des images ni conversion PDF/X.',screenHelp:'Par défaut : 120 DPI / JPEG à 78 %. Supprime le texte recherchable, l\'accessibilité et les liens. Une taille réduite n\'est pas garantie.',metadata:'Métadonnées du document',documentTitle:'Titre',author:'Auteur',subject:'Sujet',keywords:'Mots-clés (séparés par des virgules)',dpi:'DPI écran',quality:'Qualité JPEG (%)',export:'Exporter une copie',busy:'Exportation...',cancel:'Annuler',flatten:'Aplatir annotations et formulaires',flattenHelp:'Intègre les apparences visibles aux pages. Supprime les commentaires et les formulaires interactifs. Ce n\'est pas une occultation sécurisée.',standard:'Polices Standard-14',standardHelp:'Les polices existantes restent intactes. Le nouveau texte latin utilise Helvetica, Times ou Courier ; les caractères incompatibles sont refusés.',subset:'Intégrer un sous-ensemble de police',subsetHelp:'Aucun adaptateur d\'intégration ou de mise en forme des polices. Les ajouts Unicode en nécessitent un.',linearize:'Affichage web rapide (linéariser)',linearizeHelp:'Le moteur PDF actuel ne peut pas linéariser les fichiers.',pdfx:'Conversion PDF/X ou CMYK',pdfxHelp:'Aucune conversion d\'impression avec gestion des couleurs ni validation PDF/X.',unavailable:'Exportation indisponible',protected:'Les fichiers chiffrés, signés et XFA sont en lecture seule.',renderer:'Le rendu canvas est indisponible sur cette plateforme.',unsupported:'Certaines annotations n\'ont pas d\'apparence sûre ; l\'exportation s\'arrêtera au lieu de les omettre.',done:'Copie prête',invalid:'Vérifiez les paramètres d\'exportation.'},
  'pt-BR':{title:'Exportar PDF',preset:'Predefinição',print:'Impressão - preservar texto e vetores',screen:'Tela - páginas JPEG',printHelp:'Mantém fontes e imagens originais. Sem redução de imagens ou conversão PDF/X.',screenHelp:'Padrão: 120 DPI / JPEG a 78%. Remove texto pesquisável, acessibilidade e links. Um arquivo menor não é garantido.',metadata:'Metadados do documento',documentTitle:'Título',author:'Autor',subject:'Assunto',keywords:'Palavras-chave (separadas por vírgulas)',dpi:'DPI da tela',quality:'Qualidade JPEG (%)',export:'Exportar cópia',busy:'Exportando...',cancel:'Cancelar',flatten:'Achatar anotações e formulários',flattenHelp:'Incorpora as aparências visíveis nas páginas. Remove comentários e formulários interativos. Não é uma tarja segura.',standard:'Fontes Standard-14',standardHelp:'As fontes existentes não mudam. Texto latino novo usa Helvetica, Times ou Courier; caracteres incompatíveis são rejeitados.',subset:'Incorporar um subconjunto de fonte',subsetHelp:'Não há adaptador de incorporação ou composição de fontes. Adições Unicode precisam de um.',linearize:'Visualização web rápida (linearizar)',linearizeHelp:'O gravador PDF atual não pode linearizar arquivos.',pdfx:'Conversão PDF/X ou CMYK',pdfxHelp:'Não há conversão de impressão com gerenciamento de cores nem validação PDF/X.',unavailable:'Exportação indisponível',protected:'Arquivos criptografados, assinados e XFA são somente leitura.',renderer:'A renderização em canvas não está disponível nesta plataforma.',unsupported:'Algumas anotações não têm aparência segura; a exportação será interrompida em vez de omiti-las.',done:'Cópia pronta',invalid:'Confira as configurações de exportação.'},
};
